### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by SimonCropp** [ArxOne/MrAdvice#104]
Fody Version 2 is out and you will need to do an update for your addin to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency range for Fody to be at least 2.0

 Please ping me if u need help

**Comment by picrap** [comment]
Thanks Simon, unfortunately, Mr Advice doesn't use Fody anymode (at least in its master branch), so it won't require to be updated.
