### ISSUE TITLE
Dependency Injection wiring lost

### ISSUE THREAD

**Issue by BOENDAGGER** [ArxOne/MrAdvice#107]
Hi,

Thanks for the great library!

I have run into an issue where variables are lost that are setup in the constructor via the DI framework. I use StructureMap to wire the class up, this wiring instantiates a field that I need to reference in a method that I am applying advice to. _**The issue is only prevalent when I place the attribute at the top of the class, when I place the attribute on top of the method in question, all works _fine!**_

This is the relevant code:

**RepositoryClass:**
```csharp
[RepositoryExceptionAdvice] _<-- _settings is null if attribute is placed here_
public class ExampleRepository : IExampleRepository
{
  private readonly ISettings _settings;

  public ComponentTermsRepository(ISettings settings)
  {
    _settings = settings;
  }

  //Advice
  _<-- _settings is fine if attribute is placed here_
  public async Task<List<Example>> List(Guid? ExampleId)
  {
    var test = _settings.TenantId _<- Settings here is null_
  }
}

**Advice Class**
    public class RepositoryExceptionAdvice : Attribute, IMethodAsyncAdvice
    {
        public async Task Advise(MethodAsyncAdviceContext context)
        {
            try
            {
                if (context.IsTargetMethodAsync)
                {
                    await context.ProceedAsync();
                }
            }
            catch (DatabaseException e)
            {
            }
         }
      }
```

**Comment by picrap** [comment]
Hi,

did you try to place a breakpoint in the ctor and see if the `setting` value is correct? This way we can if the given `settings` parameter is null.

Thanks.

**Comment by picrap** [comment]
I tried injecting an advice at class-level but the ctor parameter is handled correctly. In a nutshell, I can't reproduce the problem and I don't see why.
Ideally, if you can extract a small sample with your problem, I will help a lot.

**Comment by picrap** [comment]
Got it! If your sample is correct, it's simply the fact that the constructor inner method (the execution point) is never invoked, since the property `context.IsTargetMethodAsync` is false for the constructor. Since you don't proceed the advice, then the constructor body is never invoked, so your field is never assigned.
I should have seen this earlier :sunglasses: .
Let me know if it's clear for you and the problem is solved.

**Comment by BOENDAGGER** [comment]
Thanks for the quick response!

I placed a breakpoint in the constructor. It seems the constructor is not called at all when the attribute is placed at the top of the class, when placed on top of the method the constructor is called as intended. This is why the _settings variable is null in the above example. Since an instance has to exist for the method invocation to happen, do you think a default constructor is used when the attribute is placed on top of the class? (Note that the class only has the one constructor defined as in above example) I can't really see why StructureMap would cause this behaviour, this is the relevant Wiring I use for StructureMap

`
Scan(scanner =>
{
    scanner.AssemblyContainingType<IInsuredGroupRepository>();
    scanner.AssemblyContainingType<InsuredGroupRepository>();
    scanner.IncludeNamespaceContainingType<IInsuredGroupRepository>();
    scanner.IncludeNamespaceContainingType<InsuredGroupRepository>();
    scanner.WithDefaultConventions();
});
`

**Comment by BOENDAGGER** [comment]
Eish, just got your second response, so you can ignore the above comment.

Yes, that was a bit stupid of me **blush**

What would the recommended way be to ignore the advice for the constructor? Would this be the best approach:

`if (!context.TargetMethod.IsConstructor) [proceed]`

**Comment by BOENDAGGER** [comment]
Ok, I made the proposed change, namely

```
public async Task Advise(MethodAsyncAdviceContext context)
{
    if (context.TargetMethod.IsConstructor)
    {
        context.ProceedAsync().Wait();
    }
    else
    {
... Continue as in original example
```
This works, if you have a preferred method, please let me know. There is no synchronous `context.Proceed` on `MethodAsyncAdviceContext`, I do not feel as comfortable with doing `context.ProceedAsync().Wait();`, would this be fine?

**Comment by picrap** [comment]
You don't have to call the `Wait()` method:
- if method is actually async it would lock until its end.
- if method is not async, then when the `ProceedAsync()` method returns, the called method is already ended (and it may deadlock the application).

And if you want to wait for an async method to end, use the `await` keyword, such as `await context.ProceedAsync()`.

**Comment by picrap** [comment]
The idea is that a `IMethodAsyncAdvice` works fine with both sync and async methods.
