### ISSUE TITLE
What about Advices excution order?

### ISSUE THREAD

**Issue by gnaeus** [ArxOne/MrAdvice#111]
Suppose we have two advices. One for throwing exceptions:
```cs
class ValidateAttribute : Attribute, IMethodAdvice {
    public void Advise(MethodAdviceContext context) {
        if (something) {
            throw new ValidationException(...);
        }
        context.Proceed();
    }
}
```
And one for logging exceptions:
```cs
class LogExceptionsAttribute : Attribute, IMethodAdvice {
    public void Advise(MethodAdviceContext context) {
        try {
            context.Proceed();
        }
        catch(Exception exception) {
            Logger.Log(exception);
            throw;
        }
    }
}
```
Then we apply it to some method:
```cs
[LogExceptions, Validate]
public void SomeMethod(SomeModel model) {
   // ...
}
```
In most cases `LogExceptions` catches exceptions from `Validate`.  
But according to the [Attribute specification](https://msdn.microsoft.com/en-us/library/aa664616(VS.71).aspx), the order of attributes is undefined.  
And for some combinations of advices in my project the execution order is broken.  
For example, `LogExceptions` will be executed before `Validate`.

Is there a bug in MrAdvice? Or it is .NET Attributes issue?  
In second case we can extend `IMethodAdvice` interface with `Order` property (like in AspNet MVC):
```cs
interface IMethodAdvice {
    int Order { set; }
}
```

**Comment by picrap** [comment]
There is a `[Priority]` attribute which applies to advices and allows to sort them :wink:

**Comment by gnaeus** [comment]
Thanks! Your library is really helpful.  
But I can not find info about `[Priority]` attribute neither in Readme nor in Wiki.

It would be nice if you add docs for this attribute.

**Comment by picrap** [comment]
There is one line about them at https://github.com/ArxOne/MrAdvice/wiki/ImplementingAdvices ... :smile: 
The `Level` property is the sort key. A higher `Level` advice is executed first.

**Comment by gnaeus** [comment]
Sorry =) Then I close this issue. Thanks a lot!
