### ISSUE TITLE
IMethodAsyncAdvice on nonAsync methods

### ISSUE THREAD

**Issue by Kahbazi** [ArxOne/MrAdvice#112]
I have these classes : 

```
public class LogAttribute : Attribute, IMethodAdvice
{
    public void Advise(MethodAdviceContext context)
    {
        Debug.WriteLine("Begin" + context.TargetMethod.Name);
        context.Proceed();
        Debug.WriteLine("End" + context.TargetMethod.Name);
    }
}

public class LogAsyncAttribute : Attribute, IMethodAsyncAdvice
{
    public async Task Advise(MethodAsyncAdviceContext context)
    {
        Debug.WriteLine("Begin" + context.TargetMethod.Name);
        await context.ProceedAsync();
        Debug.WriteLine("End" + context.TargetMethod.Name);
    }
}

public class Service
{
    public Task DoWorkAsync
    {
        // some code!
    }

    public void DoWork
    {
        // some other code!
    }
}
```

Is it ok to either use `LogAsyncAttribute` or `LogAttribute` on `DoWork` and `DoWorkAsync`?

Is using `IMethodAdvice` or `IMethodAsyncAdvice` depends on whether Advise method is `async` or not, or does it depends on pointcut methods?

**Comment by picrap** [comment]
Hi,

yes it's OK to use both: sync and async advices work both with sync and async methods.
There is one catch, anyway: if you are advising an async method with a sync advice, the code after the `context.Proceed()` call may run before the advised method has ended (in other words the returned `Task` may not have reached its `Complete` state).

So:
- if you have both async and sync methods, use async advices
- if you have only sync methods, sync advices are good enough.

Does this help?

**Comment by Kahbazi** [comment]
I'm going to use async advices.
Thanks.
