### ISSUE TITLE
AggregateException on IMethodAsyncAdvice when using await on non-async method!

### ISSUE THREAD

**Issue by Kahbazi** [ArxOne/MrAdvice#113]
I guess the title and the sample code clearly explain the issue.

```
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                AsyncAdviceTest();
            }
            catch (Exception ex)
            {
                Type type = ex.GetType(); // is Exception
            }

            try
            {
                ReallyAsyncAdviceTest();
            }
            catch (Exception ex)
            {
                Type type = ex.GetType(); // is **AggregateException**,
                // I think it should be Exception!
            }
        }

        [AsyncAdvice]
        public static void AsyncAdviceTest() => throw new Exception("Something Happened!");

        [ReallyAsyncAdvice]
        public static void ReallyAsyncAdviceTest() => throw new Exception("Something Happened!");
    }

    class AsyncAdviceAttribute : Attribute, IMethodAsyncAdvice
    {
        public Task Advise(MethodAsyncAdviceContext context)
        {
            return context.ProceedAsync();
        }
    }

    class ReallyAsyncAdviceAttribute : Attribute, IMethodAsyncAdvice
    {
        public async Task Advise(MethodAsyncAdviceContext context)
        {
            await context.ProceedAsync();
        }
    }
```

**Comment by picrap** [comment]
Thanks for reporting this. I'll take a look at it.

**Comment by picrap** [comment]
I've been thinking about this. A lot.

First of all, when a `Task` is faulted (it throws an exception), the fact of awaiting it or reading its result throws an `AggregateException` (source from the TPL team blog [here](https://blogs.msdn.microsoft.com/pfxteam/2011/09/28/task-exception-handling-in-net-4-5)).
So there is a big difference if you return directly a `Task` returned by another method (in the `AsyncAdviceAttribute` in your sample) and if you await one (meaning you read its result, internally, like in your `ReallyAsyncAdviceAttribute`).

So I think this is the responsability of the written advice to unwrap the `AggregateException` in this case.

This is like I'm saying "no I don't fix", but I really think this is not a bug.

I leave the issue open for a while, so we can discuss more about it if you like.

**Comment by Kahbazi** [comment]
Since I'm using advice for both Sync and Async methods, I end up wrapping `context.ProceedAsync` in a `try/catch`

```
 try
{
    await context.ProceedAsync();
}
catch (AggregateException ex)
{
    ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
}
```

**Comment by picrap** [comment]
That's the right thing to do (in my opinion).

**Comment by Kahbazi** [comment]
I refactored my code, but I still keep thinking that I should not get `AggregateException`, so I've been studying MrAdvice source code, and I think the reason the I'm getting `AggregateException` for async methods is the fact that there is a `Wait()` method on the Advice Task in `Invocation` class.

So I replaced `Wait()` with `GetAwaiter().GetResult()` and it works! I'm not getting `AggregateException` anymore, and I think this is the solution.

the only drawback is that `GetAwaiter()` method is not available in  .Net Framework v4 , so I had to upgrade it to .Net Framework 4.5

**Comment by picrap** [comment]
You never give up, do you? :smile: I'm sorry but I won't be able to accept the pull request, since I have some projects using Mr.Advice that still need to work with .NET 4.0.
However I keep the issue open, and I'll think (and read) about it again.

**Comment by Kahbazi** [comment]
well I try not to 😄
It's ok about the PR, but tell me if this is the correct solution if the support for .NET 4.0 is not an issue, so I can compile my own project and use it.
thanks

**Comment by Kahbazi** [comment]
Alright, I'm thinking about the ways we can do it without losing support for .Net 4.0. These two are the ways I can think of now : 

1. Wrap the `Wait()` method in a try/catch block

```
try
{
    await context.ProceedAsync();
}
catch (AggregateException ex)
{
    ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
}
```
2. Use `Microsoft.Bcl.Async` package, which adds `GetAwaiter()` as an extension method for `Task` in .Net 4.0. although your project then have dependencies to `Microsoft.Bcl.Async` , `Microsoft.Bcl.Build` and `Microsoft.Bcl`

BTW I would love it if I could submit a PR if these are the way you want to do it.

**Comment by picrap** [comment]
Hi, I'm back!

I read the documentation, again, and unfortunately, I'm right:
* `GetAwaiter()` is for internal use (https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.getawaiter(v=vs.110).aspx)
* Same thing for `GetResult()`: internal use only (https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.taskawaiter.getresult(v=vs.110).aspx)

So basically, invoking `Wait()`, like it's the case currently is the **right** (==documented) way to do things.  
As I said in my first answer, it is correct to catch an `AggregateException` when awaiting a `Task`, so even if an advice is supposed to be part of application infrastructure, the thrown exception is the correct one.

I understand that it would be convenient, but it is not the way it is supposed to work. Especially that a `Task` may have several subtasks, which could throw exceptions at the same time, so all of them would then be aggregated, thus returned in an `AggregateException` anyway (see for example `Task.WaitAll` or `Task.WaitAny`).

So I am really sorry but this is the responsibility of advice to handle this, not MrAdvice.

Again, I really dislike saying no, especially when people are nice and willing to contribute, but you need to consider the bigger picture.

I thank you for all the thinking you had me to do (it's always a good thing to question our own work).

**Comment by Kahbazi** [comment]
well to be honest I don't like to agree with you just yet! 

I read [this post](https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html) and I don't think that it's a big deal if we use `GetAwaiter().GetResult()` instead of `Wait()` , and if you still think that it's not ok to use `GetAwaiter().GetResult()` I like to think of another solution, like maybe making the `ProceedAdvice` and `ProceedAdvice2` methods `async` , so it can `await` the `task` so there would be no `AggregateException`  because I really think (wish) using advice should not affect the way Exceptions are thrown.

**Comment by picrap** [comment]
Sure, but you refer to a blog post. I refer to Microsoft documentation. Guess who's the most likely to be the authority? :wink:

**Comment by Kahbazi** [comment]
well he's a Microsoft MVP and the author of the O'Reilly Concurrency in C# Cookbook. Does that counts? 😄

and also what about the other solution, what if `ProceedAdvice` and `ProceedAdvice2` methods are async?

**Comment by Kahbazi** [comment]
I still really hope that MrAdvice would deal with `AggregateException`.

As I read these links, I think they approve using `GetAwaiter().GetResult()` instead of `Wait()` to get rid of `AggregateException`

[Parallel Programming with .NET](https://blogs.msdn.microsoft.com/pfxteam/2011/09/28/task-exception-handling-in-net-4-5/)

[Async Programming - Brownfield Async Development](https://msdn.microsoft.com/en-us/magazine/mt238404.aspx)

[Replace any Task.Result calls with Task.GetAwaiter().GetResult()](https://github.com/aspnet/Security/issues/59)

So I guess there's noting much that I can do. It's up to you now, what's your decision?

**Comment by Kahbazi** [comment]
@picrap https://github.com/aspnet/security/issues/59

**Comment by picrap** [comment]
I finally made it 😀
