### ISSUE TITLE
Duplicate type with name  'ArxOne.MrAdvice.⚡Invocation' in assembly error on rebuild

### ISSUE THREAD

**Issue by kelvinvm** [ArxOne/MrAdvice#114]
If I clean\build, it works. If I do an incremental build, I get this error when the code runs.

**Comment by picrap** [comment]
Could you give me less details? With the ones you provide, it's far too easy to find and solve the problem.

**Comment by kelvinvm** [comment]
My apologies; I was trying to be succinct.  I have written one attribute (in the attached file) which is working in an unit test. I added the attribute to a single method, and ran the code. The first time it works; the second, etc. time, I get a run time exception:

System.BadImageFormatException was unhandled
Message: An unhandled exception of type 'System.BadImageFormatException' occurred in mscorlib.dll
Additional information: Duplicate type with name 'ArxOne.MrAdvice.⚡Invocation' in assembly '[assembly]'.

If I clean\rebuild solution, then it will run one time without any errors.



[Advice.txt](https://github.com/ArxOne/MrAdvice/files/1198339/Advice.txt)

**Comment by picrap** [comment]
Hi,

MrAdvice writes an intermediate file, whose name ends with `.♥MrAdvice` beside the intermediate file. If this file is removed, the assembly may be weaved twice.
When I was asking for details about your project I meant:
* Which Visual Studio version.
* Which target
etc.
The best option would be if your had a sample to provide, of course.

**Comment by picrap** [comment]
However, since I'm nice, I made a workaround, available in version 2.5.7.
But still, please answer my questions above, it may help.
