### ISSUE TITLE
Weaving of referenced assemblies

### ISSUE THREAD

**Issue by hhblaze** [ArxOne/MrAdvice#115]
If I have in a solution several projects is there a way from one project to call weaving of the referenced dlls.

[assembly: MyAspect()]  - will weave current assembly
how to call the same process in other dlls

In postsharp it was possible via

[assembly: MyAspect(AttributeTargetAssemblies = "DllName1", AttributeTargetTypes = "*")]
[assembly: MyAspect(AttributeTargetAssemblies = "DllName2", AttributeTargetTypes = "*")]

**Comment by picrap** [comment]
Short answer: nope!
Long answer: MrAdvice operates at assembly build level, it is not solution aware at all, so it has no way to know other assemblies (other than the ones that are references by the one being built).

**Comment by hhblaze** [comment]
Ok, clear
