### ISSUE TITLE
Unexpected behaviour of Visual Studio with version 2.5.13

### ISSUE THREAD

**Issue by hhblaze** [ArxOne/MrAdvice#116]
I have a very strange behavior of Visual Studio after referring to 2.5.13, will try to explain.

When project refers to 2.5.13

![image](https://user-images.githubusercontent.com/486781/29174603-13acd9f4-7de7-11e7-80b6-a268d39aab7e.png)

It's not possible to AddReference or open NugetManager from Visual Studio, following errors:

![image](https://user-images.githubusercontent.com/486781/29174812-b67ad69a-7de7-11e7-9309-ea53de0d7cf7.png)

If this line, inside of csproj file, is remarked or removed, described functionality works again, but, of course, it doesn't weave:

![image](https://user-images.githubusercontent.com/486781/29174937-0ded4f5c-7de8-11e7-9553-f1e3fa309051.png)

If to change project to 2.5.1 all functionality works:

![image](https://user-images.githubusercontent.com/486781/29175101-6f549750-7de8-11e7-8791-b3df3fb34fde.png)

**Comment by picrap** [comment]
Confirmed! I have the same problem (which makes it easier for me to debug).
I won't have time for fixes today, maybe tomorrow or this week-end.

**Comment by picrap** [comment]
Fixed in 2.5.15 :face_with_head_bandage:

**Comment by hhblaze** [comment]
Omg, sun, beach, girls ASAP ;)

And thank you for the relese, will test ASAP!

**Comment by picrap** [comment]
Enjoy it all (sun, beach, girls... Mr Advice)!

**Comment by hhblaze** [comment]
Hah, I wanted actually to advice you to switch to the sun, beach...after fixing bugs :)

**Comment by hhblaze** [comment]
This problem fixed
