### ISSUE TITLE
Passing parameters to multiple instances of same aspect?

### ISSUE THREAD

**Issue by kondotak** [ArxOne/MrAdvice#117]
Is there a way to share state among different instances of the same aspect?  I am currently using HttpContext.Current.Items to pass "per request" scoped state within asp.net.  Any alternatives in MrAdvice that I could leverage?  Thanks!

**Comment by picrap** [comment]
What scope do you want for your data? You can introduce fields per instance (see [here](https://github.com/ArxOne/MrAdvice/wiki/IntroducingFields)), but a call context does not exist, since it's out of Mr Advice scope.
