### ISSUE TITLE
Unnecessary thread change during the execution of a sync method which is being advised by an async advice

### ISSUE THREAD

**Issue by davidnemeti** [ArxOne/MrAdvice#120]
Hi,

I found a problem with advising a **sync method** with an **async advice**. The problem is that currently an async advice (which implements the `IMethodAsyncAdvice` interface) unnecessarily **changes the current thread** after the execution of the method, in spite of the implementation of the async advice being purely sync (i.e. the advice itself does not do anything async, it just simply proceeds with the advised method).

So currently the following example:

```csharp
    class Program
    {
        static async Task Main(string[] args)
        {
            WriteLine($"MyProudMethod BEFORE {Thread.CurrentThread.ManagedThreadId}");
            MyProudMethod();
            WriteLine($"MyProudMethod AFTER {Thread.CurrentThread.ManagedThreadId}");

            WriteLine();

            WriteLine($"MyProudMethodAsync BEFORE {Thread.CurrentThread.ManagedThreadId}");
            await MyProudMethodAsync();
            WriteLine($"MyProudMethodAsync AFTER {Thread.CurrentThread.ManagedThreadId}");
        }

        [MyProudAdvice]
        static void MyProudMethod()
        {
            WriteLine($"MyProudMethod {Thread.CurrentThread.ManagedThreadId}");
        }

        [MyProudAdvice]
        static async Task MyProudMethodAsync()
        {
            WriteLine($"MyProudMethodAsync BEGIN {Thread.CurrentThread.ManagedThreadId}");
            await Task.Delay(1);
            WriteLine($"MyProudMethodAsync END {Thread.CurrentThread.ManagedThreadId}");
        }
    }

    public class MyProudAdvice : Attribute, IMethodAsyncAdvice
    {
        public async Task Advise(MethodAsyncAdviceContext context)
        {
            WriteLine($"Async Advise BEGIN: {context.TargetMethod.Name} {Thread.CurrentThread.ManagedThreadId}");

            await context.ProceedAsync();

            WriteLine($"Async Advise END: {context.TargetMethod.Name} {Thread.CurrentThread.ManagedThreadId}");
        }
    }
```

shows this output (I edited it, so it includes my comments):

```
MyProudMethod BEFORE 1
Async Advise BEGIN: MyProudMethod 1
MyProudMethod 1
Async Advise END: MyProudMethod 3    // unnecessary thread change!
MyProudMethod AFTER 1   // here we are back to the original thread

MyProudMethodAsync BEFORE 1
Async Advise BEGIN: MyProudMethodAsync 1
MyProudMethodAsync BEGIN 1
MyProudMethodAsync END 4
Async Advise END: MyProudMethodAsync 4
MyProudMethodAsync AFTER 4
```

The problem goes away after fixing MrAdvice's `Tasks.Void` method by changing its implementation from this:

```csharp
        public static Task Void()
        {
            if (_void == null)
            {
                var @void = new Task(() => { });
                @void.Start();
                _void = @void;
            }
            return _void;
        }
```

to this:

```csharp
        public static Task Void()
        {
            if (_void == null)
            {
                var tcsVoid = new TaskCompletionSource<object>();
                tcsVoid.SetResult(null);
                _void = tcsVoid.Task;
            }
            return _void;
        }
```

Of course, the best solution would be to use .NET's `Task.CompletedTask` method, but I know that it does not exist in .NET 4.0, that is why `Tasks.Void` had to be introduced.

After the fix the previous example shows this output, where there are no unnecessary thread changes during the execution of the sync method:

```
MyProudMethod BEFORE 1
Async Advise BEGIN: MyProudMethod 1
MyProudMethod 1
Async Advise END: MyProudMethod 1
MyProudMethod AFTER 1

MyProudMethodAsync BEFORE 1
Async Advise BEGIN: MyProudMethodAsync 1
MyProudMethodAsync BEGIN 1
MyProudMethodAsync END 4
Async Advise END: MyProudMethodAsync 4
MyProudMethodAsync AFTER 4
```

**Comment by picrap** [comment]
Relevant. Implemented. Release 2.5.17. Thanks!
(yeah, I'm brief, but happy 🎉)

**Comment by picrap** [comment]
Almost 😢 The build is failing; give me a couple of hours to fix it (but first, I need to go to the supermarker for shopping).

**Comment by picrap** [comment]
Finally released! Thanks again!

**Comment by davidnemeti** [comment]
You are welcome! :-) Thanks for the quick release!

I would have created a pull request, but I could not build the whole solution due to some build errors, so I rather wrote the solution in my comment. However, after I pulled your changes, now I can build the solution.

**Comment by picrap** [comment]
What errors did you get? If it was an expired certificate, I removed the UwpTest assembly from solution.

**Comment by davidnemeti** [comment]
It was some kind of weaving related error: the building of the test projects failed, because it did not find the build/MrAdvice.Weaver.exe (despite that it was definitely there) or the task inside (unfortunately, I do not remember the details), and it said that I should check the `UsingTask` element.

I think that the VS restart and solution reload solved the problem eventually.
