### ISSUE TITLE
DateTime out variable leads to Runtime crash

### ISSUE THREAD

**Issue by hhblaze** [ArxOne/MrAdvice#121]
Hi, got another bug, that can be completely simulated (see attached project).
[TestMrAdvice2.zip](https://github.com/ArxOne/MrAdvice/files/1441454/TestMrAdvice2.zip)

**Comment by picrap** [comment]
Hi, I released a version 2.5.19. Let me know if it fixes the bug.

**Comment by hhblaze** [comment]
Very well, thank you!
