### ISSUE TITLE
Can't load MrAdvice assembly (WTF?), exiting

### ISSUE THREAD

**Issue by Thorocaine** [ArxOne/MrAdvice#123]
I am having this annoyance.

I am using Xamarin forms to develop an Android application and using MrAdvice (which I am loving for small things, like run on the main thread or set a flag to busy while this method is running).

The annoying part is that I need to remove it and then re-add it every time I want to execute the application.

I have the NuGet installed on my shared project (.NetStandard) and on the Android project. When I want to run the applications, it builds (successfully), and then MrAdvice dies...

```
    1>Done building project "Igs.Mobile.RoadStop.Android.csproj".
    1>Build succeeded.
    1>Can't load MrAdvice assembly (WTF?), exiting
    1>
```

I remove the NuGet (just from the Android project), add it again, and it builds, and runs without any trouble.

I would be happy to send any logs (if you tell me where to find them) or do any testing.

**Comment by picrap** [comment]
Sorry to read that. What if you restart your build environment (your IDE, I mean, not your OS)? Does it help?
I'm aware of this problem, I also get it sometimes, but I was never able to resolve it. I'll take a look at it again this week-end.

**Comment by Thorocaine** [comment]
reinstalling the NuGet sorts it out straight away, but it comes up again every half an hour or so.

Restarting VS (Windows) might help, but reinstalling the NuGet would be quicker, so I have never tried.
It has been happening for a month or two, so restarting VS, or PC isn't a "final" solution.

**Comment by picrap** [comment]
Of course restarting VS is not a final solution, only a fix would be 😄

**Comment by picrap** [comment]
I released a version named `MrAdvice.2.5.18-exp3` (accessible if you enable the pre-releases listing). Could you give it a try?
(this is a blind test, so don't expect too much from it anyway).

**Comment by Thorocaine** [comment]
I will do that.

**Comment by picrap** [comment]
There is a `MrAdvice.2.5.18-exp4` with early diagnostic.

**Comment by Thorocaine** [comment]
Thanks, I have just gotten back to work, and I see there is now a .19
Should I be using 19, or 18-exp4?

**Comment by picrap** [comment]
Hi, I was about to tell you that you can try the version 2.5.19, so yes, go for it.

**Comment by Thorocaine** [comment]
Not yet, sorry, it seems with Xamarine there are a hundered other things
that can start breaking when chaning something.
I can't remember if I left it on the latest or not.
I will let you know later today if it is running.

**Comment by Thorocaine** [comment]
Hi, I am sorry I have been so quiet on this.
I am still using 2.5.17, but I haven't gotten this error in a while.
I am not sure what may have changed, maybe something in Xamarin or VS updated.

**Comment by picrap** [comment]
OK, I keep the issue open until february. If the issue comes back after that, you can either reopen this issue or create a new one. Thanks for feedback.

**Comment by picrap** [comment]
`dnlib` was improved, apparently 🤔 
I'll see if there are other options to generate PDB and let you know.

**Comment by picrap** [comment]
Give 2.5.26 a try (it may not work, since I made blind changes for this).

**Comment by picrap** [comment]
Is it still not working?

**Comment by rgroenewoudt** [comment]
Ah, yes it's working! Thank you. You can close this ticket.

**Comment by picrap** [comment]
I am the first to be surprised, but OK :)
