### ISSUE TITLE
Mr Advice and Fody

### ISSUE THREAD

**Issue by advapiIT** [ArxOne/MrAdvice#125]
Hello,
It's possible to have MrAdvice and Fody (I'm using Catel framework and make huge use of Fody) to live together? as I've seen no... since I got error on build on

 >Severity	Code	Description	Project	File	Line	Suppression State
Error		Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/SVN/Projects/xx/xxx/trunk/packages/MrAdvice.2.0/build
LOG: Initial PrivatePath = NULL
Calling assembly : MrAdvice.Weaver, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.0.0.0 redirected to 15.1.0.0.
LOG: Post-policy reference: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/SVN/Projects/xx/xx/trunk/packages/MrAdvice.2.0/build/Microsoft.Build.DLL.
LOG: Attempting download of new URL file:///C:/SVN/Projects/xx/xx/trunk/packages/MrAdvice.2.0/build/Microsoft.Build/Microsoft.Build.DLL.
LOG: Attempting download of new URL file:///C:/SVN/Projects/xx/xx/trunk/packages/MrAdvice.2.0/build/Microsoft.Build.EXE.
LOG: Attempting download of new URL file:///C:/SVN/Projects/xx/xxx/trunk/packages/MrAdvice.2.0/build/Microsoft.Build/Microsoft.Build.EXE.

   at StitcherBoy.Project.ProjectDefinition..ctor(String path, String outputDirectory, IDictionary`2 globalProperties, IAssemblyResolver assemblyResolver)
   at StitcherBoy.Weaving.SingleStitcher.Process(String assemblyPath, String projectPath, String solutionPath, String configuration, Guid buildID, DateTime buildTime, String entryAssemblyPath)
   at StitcherBoy.Weaving.StitcherProcessor.Process(String assemblyPath, String projectPath, String solutionPath, String configuration, Guid buildID, DateTime buildTime, String entryAssemblyPath)
   at StitcherBoy.Weaving.StitcherProcessor.Process(String assemblyPath, String projectPath, String solutionPath, String configuration, Guid buildID, DateTime buildTime, String entryAssemblyPath)
   at StitcherTask`1.Run(Boolean fromExe)	IF.xxx.Modules.Batch

**Comment by picrap** [comment]
Fixed by bug reporter :)
