### ISSUE TITLE
Instruction was removed from the body but is referenced from PdbScope

### ISSUE THREAD

**Issue by hhblaze** [ArxOne/MrAdvice#130]
Hi, very often appears this error by compiling (Mr.Advice 2.5.24). But, by cleaning \obj and \Release folders, cleaning project, restarting Visual Studio, it disappears and lets to compile the project:

![image](https://user-images.githubusercontent.com/486781/39430040-fa912680-4c8c-11e8-9f8b-a0bea8ac254f.png)

**Comment by picrap** [comment]
Is it possible that the assembly is weaved twice? After processing, MrAdvice generates a `.♥MrAdvice` file beside the weaved assembly. If this file is missing, it may weave the same assembly twice.

**Comment by hhblaze** [comment]
This guy  .♥MrAdvice appears after weaving in the obj/Debug(Release) folder, but not in bin/Release. After deleting files and folders inside the obj/Debug(Release), but leaving files in bin/Debug(Release) - error CAN occur.

**Comment by picrap** [comment]
Still happening? (I’m cleaning up old issues, since version 2.9 has a new weaver)
