### ISSUE TITLE
MrAdvice not working when using the .NET Core version of msbuild (dotnet publish)

### ISSUE THREAD

**Issue by hhblaze** [ArxOne/MrAdvice#133]
Hi, I got following issue, that is not about MrAdvice functionality, but about its evolution.
There is a .NetCore [project HelloWorld1.zip](https://github.com/ArxOne/MrAdvice/files/2213673/HelloWorld1.zip) that can be compiled into native win-x64 binary using [CoreRT](https://github.com/dotnet/corert/tree/master/samples/HelloWorld), after adding via Nuget 2.5.24 MrAdvice compiling into native fails:

D:\Temp\hw\HelloWorld1>dotnet publish -r win-x64 -c release

C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\MrAdvice.targets(10,5): error MSB4062: Can't load task "MrAdviceTask" from assembly "C:\Users\blaze\.nuget\packages\mradvice\2.5.24\build\..\build\MrAdvice.Weaver.exe". Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Can't find file. Check declaration <UsingTask>, accessebility of the assembly with all its dependecies
and existance a common class in the task, implementing Microsoft.Build.Framework.ITask. [D:\Temp\hw\HelloWorld1\HelloWorld1.csproj]

![image](https://user-images.githubusercontent.com/486781/43000158-a88bc088-8c20-11e8-8f3a-b5e8b554e0f7.png)

**Comment by picrap** [comment]
Feel free to contribute :)

**Comment by picrap** [comment]
Thinking about this, a good option would be to provide a standalone command-line weaver, without any dependency, so it could run on .NET Core.

**Comment by AlexanderButs** [comment]
consider dotnet tool to make this possible :)

**Comment by picrap** [comment]
Yeah, the only thing required now is some guy to implement this... 😉

**Comment by picrap** [comment]
So, since people ask, how about using the `MrAdvice.Weaver.exe` in command line (cause it already does)? Would this help, until someone comes up with a more integrated solution.

**Comment by fredmabire** [comment]
Is Mr Advice.Weaver.exe platform agnostic ? It seems that it depends on Framework 4.5.

**Comment by picrap** [comment]
Yes, but all it needs is to be invoked as a command-line application.

**Comment by picrap** [comment]
I wrote a quick reference at https://github.com/ArxOne/MrAdvice/wiki/CommandLineWeaver... If anyone wants to give it a try in a custom build, you're welcome.

**Comment by picrap** [comment]
Hi there, there is a preview of 2.9 where I rewrote the build task. Could you tell me if it is working with `dotnet build`?

**Comment by picrap** [comment]
Works!
