### ISSUE TITLE
Special Character Issue

### ISSUE THREAD

**Issue by PankajRawat333** [ArxOne/MrAdvice#136]
After using "MrAdvice" Nuget, I'm not able to zip my project folder due to special character CAT.AMS.Functions.dll.♥MrAdvice.

**Comment by picrap** [comment]
Hi, you don't need this file. It is created in `obj` folder, which contains only temporary files.

**Comment by PankajRawat333** [comment]
yes, everytime I need to delete this file manually

**Comment by picrap** [comment]
Won’t do (because 🤪).
