### ISSUE TITLE
Add standard advices

### ISSUE THREAD

**Issue by furesoft** [ArxOne/MrAdvice#137]

**Comment by picrap** [comment]
?

**Comment by picrap** [comment]
??

**Comment by picrap** [comment]
@furesoft is you want something, please explain.

**Comment by furesoft** [comment]
like these advices:
logging, permissions, different design patterns

**Comment by furesoft** [comment]
like:
`
[FluidApi]
public class helloapi {
    public void DoSomething() {...}
}
`

turns into:
`
public class helloapi {
public helloapi DoSomething() { return this;}
}`

**Comment by picrap** [comment]
That's nice (I like this kind of methods), however the change has to be made before build, not after (it changes déclaration, not implementation). Since MrAdvice works at post-build, this is not possible at all, unfortunately.
