### ISSUE TITLE
Disabling MrAdvice in unit testing

### ISSUE THREAD

**Issue by rhap06** [ArxOne/MrAdvice#148]
I would like to know if it's possible to disable MrAdvice in a clean way when we run our unit tests. I have 3 advices that are set on Assembly level and I would like to either Substitute it or just disable it.

Edit: I know postsharp has a flag to disable it. I wouldn't call that clean but if you did the same feature, I would use it: https://stackoverflow.com/questions/14691554/how-do-you-disable-postsharp-when-running-unit-tests.

Thanks,

**Comment by picrap** [comment]
Hi,

currently there is no way to do so. How would like this feature?

**Comment by rhap06** [comment]
Hi,

Could there be a way like the exclude pointcut where you specify the caller namespace and if filters out when the condition is met? Like this:
`[ExcludeCaller("MyApplication.UnitTests*")]`
Or have a way to access MrAdvice configuration at runtime to modify it or just have an activate flag somewhere in MrAdvice.

If that can help you, for now what I'm doing is that (it's very clean either but it's our only way of knowing surely we're running unit tests):
`const string testAssemblyName = "Microsoft.VisualStudio.QualityTools.UnitTestFramework";`
`IsInUnitTest = AppDomain.CurrentDomain.GetAssemblies().Any(a => a.FullName.StartsWith(testAssemblyName));` and in our base advice I must verify if we're in unit test and just do the context.proceed().

Thanks!

**Comment by picrap** [comment]
You can already exclude an advice from being added in a pointcut with the attribute `[ExcludePointcut("*")]`. This attribute applies to advices (the ones who implement `I*Advice`).

**Comment by rhap06** [comment]
Yeah I know, I'm already using it. I didn't explain myself correctly, what I meant was that we're using MrAdvice in a DLL and the ExcludePointcut will just let me exclude everything in the namespace of the DLL. But my method is called from my unit test in another project with a different namespace. So in the current method context I don't have a reference to the unit test project, only the DLL containing the method with the advice on.

**Comment by picrap** [comment]
I'm sorry I don't understand. If you use the `ExcludePointcutAttribute`, no method is going to be injected, whatever its assembly is. Using this, it will be disabled everywhere. Is this not what you wanted?

**Comment by rhap06** [comment]
Maybe it's me that don't understand but if I want the advice to work anytime except when we run unit test, it won't work right? Because if I use `[ExcludePointcut("*")]` it won't run anytime.

**Comment by picrap** [comment]
So do you want the same assembly, issued from one single build to be sometimes advised and sometimes not?
Mr Advice is a build step that actually transforms the assembly, changes the advised methods to invoke the runtime part, so once it is built, it is _de facto_ advised. It can not be unbuilt.
But you can add a global field somewhere that your advices can access to disable their own behavior.

**Comment by rhap06** [comment]
Yeah that's exactly what I want, from the way it looks it won't be possible. But I would love to have a way of skipping the advice only when we are running unit tests. Because as of now we are calling the advice and it could have an impact on our unit tests when we don't want to. 

As a matter of fact, the solution that I did is exactly what you proposed. I have a static variable finding if we're running unit tests and we just skip the whole process in the advice and just do `context.proceed();`.

**Comment by picrap** [comment]
OK, so let's close!
