### ISSUE TITLE
Notify of calling BCL methods

### ISSUE THREAD

**Issue by vbcodec** [ArxOne/MrAdvice#151]
Does this tool enable to notify when code calls specific method from NET library ? For example I want to intercept all calls to String.Join() or ToLower().

**Comment by picrap** [comment]
Hi, MrAdvice only applies to assemblies **you** build. So no `string.Join` or `string.ToLower()` (unless you build them 😉).

**Comment by vbcodec** [comment]
But I meant something diffrent. I do not want to modify body of String.Join(). Instead I want that MrAdvice will modify my generated code that call String.Join().

For example code:
...
String.Join (p1, p2);
...

will be replaced with 
...
\u26A1Invocation.ProceedAspect (...)
...

Hopefully, such functionality will be added, if not exist now :)

**Comment by picrap** [comment]
I wasn't clear, then. But still, the code is added to the invoked method, not the invoker. So currently, it does not what you want.  
However, volunteers are welcome to implement this...
