### ISSUE TITLE
Using MrAdvice with Unity

### ISSUE THREAD

**Issue by loic-lopez** [ArxOne/MrAdvice#152]
Hi,

Is it possible to use MrAdvice with an Unity project?

I have successfully load the MrAdvice.dll but my Advice:

```csharp
///////////////////////////////////////////////////////////
//  Logger.cs
//  Implementation of the Class Logger
//  Generated by Enterprise Architect
//  Created on:      26-oct.-2019 17:07:59
//  Original author: Loic
///////////////////////////////////////////////////////////

using System;
using ArxOne.MrAdvice.Advice;
using UnityEngine;

namespace Arch.Internal.Advices
{
    public class MethodLogger : Attribute, IMethodAdvice
    {
        /// 
        /// <param name="context"></param>
        public void Advise(MethodAdviceContext context)
        {
            Debug.Log("LOGGER");
            context.Proceed();
        }
    }
}
```

does not print in the debug console (at editor runtime) the text "LOGGER"

Thanks for reply.

**Comment by picrap** [comment]
A silly question: do you apply the advice you wrote? On the assembly? On a type? On a method?

**Comment by loic-lopez** [comment]
```
using UnityEngine;
using Arch.Internal.Advices;

public class SceneEventManager : MonoBehaviour
{
   [MethodLogger]
   public void Test()
   {
      Debug.Log("Invoked Test");
   }

   private void Update()
   {
       if (Input.anyKeyDown)
       {
                Test();
       }
   }
}
```

**Comment by picrap** [comment]
That seems fine :)
How do you build your application? MrAdvice works for sure when using Visual Studio, does not work for sure using dotnot build, and for anything else, I don't know.

**Comment by loic-lopez** [comment]
Also unity does not support Nuget packages so I have manually added the dll in the Plugins directory

**Comment by loic-lopez** [comment]
I think my build is not calling the .targets file

**Comment by loic-lopez** [comment]
see: [https://stackoverflow.com/questions/58573452/how-to-use-unity-mradvice-postsharp-free-alternative-for-logging-a-class-met](https://stackoverflow.com/questions/58573452/how-to-use-unity-mradvice-postsharp-free-alternative-for-logging-a-class-met)

**Comment by picrap** [comment]
You have your answer then: MrAdvice advice works at build step by chaning the generated code. So if it is not invoked, there's no chance it will do anything.

**Comment by loic-lopez** [comment]
So if i found a solution by adding the .targets in build .csproject maybe it will work?

**Comment by picrap** [comment]
Yes.

**Comment by loic-lopez** [comment]
What are the parameters of MrAdvice.Weaver.exe?

**Comment by loic-lopez** [comment]
@picrap Or do you know how to call the MrAdvice.targets without nuget? for exemple in a `after.{solutionname}.sln.targets`

**Comment by picrap** [comment]
There is a small documentation about command line here: https://github.com/ArxOne/MrAdvice/wiki/CommandLineWeaver

**Comment by picrap** [comment]
There is a 2.9 version with a new assembly weaver, try it and let me know
