### ISSUE TITLE
Documentation / examples regarding weaving levels

### ISSUE THREAD

**Issue by Expecho** [ArxOne/MrAdvice#155]
From the README:

> Advise methods or parameters, at assembly, type, method or parameter level

I could only find tests for the assembly and method level. How can I / Where do I find examples of weaving at type level?

**Comment by picrap** [comment]
```
[MyAdvice]
class MyClass
{
}
```
This will advise all methods in class.

**Comment by Expecho** [comment]
Thanks. Updated [the Wiki](https://github.com/ArxOne/MrAdvice/wiki/UsingAdvices)

**Comment by picrap** [comment]
Thanks! I had no idea it was even possible to update the wiki for non-members...

**Comment by Expecho** [comment]
> Thanks! I had no idea it was even possible to update the wiki for non-members...

Nor did I to be honest :-)
