### ISSUE TITLE
netstandard2.1 support

### ISSUE THREAD

**Issue by PankajRawat333** [ArxOne/MrAdvice#159]
I would like to use MrAdvice with netstandard2.1 with Blazor, currently not able to use with 2.1

**Comment by hhblaze** [comment]
Having the fact that we soon all have to move to .NET 5, it becomes a very actual question...

**Comment by picrap** [comment]
I know… I’m working on it, on my sparse free time.

**Comment by PankajRawat333** [comment]
@picrap When you are planning a new release with netstandard2.1?

**Comment by picrap** [comment]
It’s still in (slow) progress…

**Comment by hhblaze** [comment]
:) .Net 5 is out and we need to resurrect this beautiful piece of software!

**Comment by picrap** [comment]
It’s not dead!

**Comment by picrap** [comment]
It’s working!
