### ISSUE TITLE
Targeting assembly advice not working correctly

### ISSUE THREAD

**Issue by sachinmani** [ArxOne/MrAdvice#164]
When targeting the assembly for advice, the advice is applied on the method outside the assembly and it creates too much noise.
I have an integration class where i want to advice on diagnostics, the method in the class makes an external call on Http, I was expecting that the advice would be only applied to the method but not to external call. 
I think it is a bug, could we apply a fix to apply advice on only assembly methods not to thridparty dll method calls

**Comment by picrap** [comment]
Well, there is a misunderstanding somewhere, because it is sure that MrAdvice only advises the target assembly. Could you show me a few line of codes with what’s advised and should not?
