### ISSUE TITLE
Wrong order of advices in class libraries

### ISSUE THREAD

**Issue by Skildpadde420** [ArxOne/MrAdvice#170]
When using advices for validation of method parameters, the order in which they get executed is not the same as written in the class library.
For example, we have a method called DoSomethingWithAFile([NotEmpty][FileExist] string filepath) inside a class library. We call the method from a console application. If we hand the method a String.Empty (""), we would expect an ArgumentNullException from the NotEmpty-Advice. Instead we get a FileNotFoundException from the FileExist-Advice.

If the same method is written in the console application, we would get the ArgumentNullException as expected. 

When having more than 2 advices, the order can be in the right order (from left to right), or even backwards (right to left). 
Also worth noting is that the build process of the library orders the Advices visually alphabetical. 

Is there a way to influence the order of the Advices consistently?

If you need code examples, we can provide you those.

**Comment by picrap** [comment]
Hi. Unfortunately .NET does not guarantee attributes order, this is why Mr. Advice has the `[Priority]` attribute you’ve always dreamt of 😎.
Apply it to your advices, specify a value (higher value means higher priority). See https://github.com/ArxOne/MrAdvice/wiki/ImplementingAdvices#markers-for-advices for a few more details.

**Comment by Skildpadde420** [comment]
Many thanks for your answer which explains the behavior of .NET. I just had a look into it and noticed that it is only applicable on class and structs. Is there a way to support the priority of attributes on parameters?

**Comment by picrap** [comment]
Priority is on advices, so apply it on advices, and apply advices to your parameters.

**Comment by Skildpadde420** [comment]
I am aware that the priority is on advices, but as I mentioned before is that the usage is limited to only classes and structs, which is also stated in the PriorityAttribute.cs Code: 

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
    public class PriorityAttribute : Attribute

With the example from beginning: DoSomethingWithAFile([NotEmpty(2)][FileExist(1)] string filepath) (Now with the priority) 
I have implemented the priority attribute via inheritance, with the change of the target to AttributeTargets.Parameter without any different results, except the removal of the error message and the same behavior in random order.

Therefore it gives an error if applied on parameter scope. The limited target must be there for some reason and I don't know if I am missing something here. 

Many thanks for your reply in advance and sorry for the inconvenience.

**Comment by picrap** [comment]
If your `NotEmpty` and `FileExist` are advices, it means they are classes. If you apply `Priority` to them, you don’t need to do anything else. Each time those two will be applied somewhere (class, parameter…), they will be sorted so `NotEmpty` will be processed first. If not, that’s a bug 😉
