### ISSUE TITLE
Failed to resolve assembly: System.Private.CoreLib, Version=5.0.0.0

### ISSUE THREAD

**Issue by Alex-Dobrynin** [ArxOne/MrAdvice#174]
After updating to version 2.9.2 I get this error
Error		Failed to resolve assembly: 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'

Xamarin.Forms 5, .netstandard2.1, c#9

**Comment by picrap** [comment]
We had problems with `System.Private.CoreLib` but this wasn’t related directly by the lib we use (dnlib). Could you provide a sample?

**Comment by Alex-Dobrynin** [comment]
It is very strange. In my test project it is working. but in my main project fails to compile. everything same, except few nuget packages.

**Comment by Alex-Dobrynin** [comment]
OK, it is happens when upgrading from 2.8.12 to 2.9.0-test1. with 2.8.12 works well, with 2.9.0-test1 cannot compile

**Comment by picrap** [comment]
We’ll give a try building for .net standard 2.0, then.

**Comment by picrap** [comment]
Instead of writing non-sense (.net standard is NOT a framowork, it’s a standard), could you tell which weaver is used? 😉

**Comment by Alex-Dobrynin** [comment]
just screenshot from nuget
![image](https://user-images.githubusercontent.com/23138430/154705670-2c431fba-7283-47aa-8b45-d061729ea764.png)

**Comment by picrap** [comment]
Could you tell which MrAdvice.Weaver.exe is used? (you still didn’t get it bout .net standard, but this is not the point)

**Comment by Alex-Dobrynin** [comment]
[BlankApp1.zip](https://github.com/ArxOne/MrAdvice/files/8098124/BlankApp1.zip)
here is sample project, there you can figure out, that core project is .netstandard project and it cannot be build using your latest lib. if you remove all mentions of your lib it can be built successfully. 
I don't know MrAdvice.Weaver.exe is used

**Comment by picrap** [comment]
For your information on .net standard, please go read https://docs.microsoft.com/en-us/dotnet/standard/net-standard
But thank you for the sample which says:
`MrAdvice 2.9.6/.NET 5.0 weaved module 'BlankApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' (targeting framework ) in 296ms`
So I guess this was the .net 5.0 weaver 😉

**Comment by Alex-Dobrynin** [comment]
.net5 is not supported by xamarin forms

**Comment by picrap** [comment]
That’s why I’ll try to use the .NET 4.6.1 weaver

**Comment by Alex-Dobrynin** [comment]
.net framework also is not supported by xamarin

**Comment by picrap** [comment]
MrAdvice.Weaver 2.8 was only built in .NET framework. And is working for your case.

**Comment by Alex-Dobrynin** [comment]
And it is strange

**Comment by Alex-Dobrynin** [comment]
Found the problem, you need to add this 

netstandard2.0

here

![image](https://user-images.githubusercontent.com/23138430/200124544-065e4310-89e5-4159-b02c-3381414d1a6e.png)

and it will work in netstandard libs, tested in my project locally

**Comment by picrap** [comment]
https://www.nuget.org/packages/MrAdvice/2.9.9 Let me know!
