### ISSUE TITLE
Incorrect version in MrAdvice.dll

### ISSUE THREAD

**Issue by MrMoonCH** [ArxOne/MrAdvice#176]
The File version and the Product version of the MrAdvice.dll file is not set correctly.
Affects Package 2.9.2

Could you please fix this issue. We have problems to update to the latest version due to lower version numbers.

Thanks..

**Comment by picrap** [comment]
Thank you, sorry for that, it should be OK in version 2.9.3… Let me know 😅

**Comment by MrMoonCH** [comment]
Thanks for your fast fix. The Product version seems to be correct now. Unfortunately the File Version is still on 2.0.0.0
![image](https://user-images.githubusercontent.com/95072504/143826211-8fbd6ad0-cd1b-40fc-bc91-a202aa6b84f1.png)

**Comment by picrap** [comment]
Yes, that was on purpose, to allow compatibility. Are you still stuck?

**Comment by MrMoonCH** [comment]
Yes I'm still stuck. Because version 2.8.8 had a file version of 2.8.8.0 
![image](https://user-images.githubusercontent.com/95072504/143871057-b800ac25-43a3-4577-aeee-2a29c682f1ee.png)
My installer seems to have a problem with an increase of Product version and a decrease in File version.

**Comment by picrap** [comment]
OK, sorry to read that, I’ll fix tonight (french hour). If you’re in a hurry, please submit a pull request.

**Comment by picrap** [comment]
Fixed again… Hopefully. Version 2.9.4.

**Comment by MrMoonCH** [comment]
Perfect, thank you very much.. The installer works now as expected again. 

By the way I'm using "advanced installer 18.9" which has problems to update a file with lower file version and higher product version.

**Comment by picrap** [comment]
Good to know, thank you.

**Comment by wilhelmmedetz** [comment]
When using 2.9.4 I get the following warning:

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Found conflicts between different versions of "MrAdvice" that could not be resolved.
There was a conflict between "MrAdvice, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8, processorArchitecture=MSIL" and "MrAdvice, Version=2.9.4.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8".
    "MrAdvice, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8, processorArchitecture=MSIL" was chosen because it was primary and "MrAdvice, Version=2.9.4.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8" was not.
    References which depend on "MrAdvice, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8, processorArchitecture=MSIL" [].
        Unresolved primary reference with an item include of "MrAdvice, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8, processorArchitecture=MSIL".
    References which depend on "MrAdvice, Version=2.9.4.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8" [].
        C:\Dev\Abc-CA\Abc.Def.Core\packages\Abc.Diagnostics.2.5.0-prerelease.2.beta\lib\net472\Abc.Diagnostics.dll
          Project file item includes which caused reference "C:\Dev\Abc-CA\Abc.Def.Core\packages\Abc.Diagnostics.2.5.0-prerelease.2.beta\lib\net472\Abc.Diagnostics.dll".
            Abc.Diagnostics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=251a3ce1bec1fe55, processorArchitecture=MSIL
            C:\Dev\Abc-CA\Abc.Def.Core\Abc.Def.Core\bin\Debug\net472\Abc.Def.Core.dll	Abc.Def.Config			

When going back to 2.9.1 the warning disappears.

The solution contains old csproj files and new SDK-style csproj files. All projects target net472.

In a solution containing only new SDK-style csproj files the warning does not occur.

**Comment by picrap** [comment]
I’ll try to fix this this week, but we’ll probably come back to original versioning (where assembly version is always 2.0, only file version changes).

**Comment by picrap** [comment]
There is a new version where:
- package and file versions are 2.9.5
- MrAdvice assembly version is 2.0
- MrAdvice file version is 2.9.5
It’s getting back to the original design, which was lost during `csproj` migration to SDK-style.
