### ISSUE TITLE
Class library aspects are not waved into destination classes

### ISSUE THREAD

**Issue by karolszmaj** [ArxOne/MrAdvice#19]
Hi,
I'm wondering about aspect separation for projects. For example I want to have:
ProjName.Aspects
ProjName.Client

Client want to use aspects from library but unfortunatelly they are not injected into classes in Client project. If aspects are defined in Client project everything works fine.

**Comment by picrap** [comment]
Confirmed:
`MSBUILD : warning : Fody/Weavers: IAdvice interface not found here, exiting`

**Comment by picrap** [comment]
Fixed in version 0.3.6. Thanks for submitting bugs!
