### ISSUE TITLE
No compatible code running on the thread

### ISSUE THREAD

**Issue by Alex-Dobrynin** [ArxOne/MrAdvice#197]
If I have somewhere aspects and methods with aspect attribute (the module is weaved) and I run async/await code in main thread and put there breakpoints I get this error.

If remove MrAdvice nuget and comment everything related to this lib, breakpoints will be reached without any problems

I'm using .net7

Here is the code I run:
![image](https://github.com/ArxOne/MrAdvice/assets/23138430/53622ae6-7c2a-42a9-8e46-dbcd0938b599)

Here is the error I get:
![image](https://github.com/dotnet/maui/assets/23138430/a22e6a2d-7db4-4109-82e2-ba8c041007e1)

Here is repro
[ErrorSample.zip](https://github.com/ArxOne/MrAdvice/files/12111942/ErrorSample.zip)

**Comment by picrap** [comment]
MrAdvice may trigger it, but is probably not the cause: https://stackoverflow.com/questions/69836969/debugging-issue-with-vs-2022-and-net-maui

**Comment by XuLinFei** [comment]
I also encountered the same problem, but I upgraded to the latest SDK of net6 and it didn't work. I introduced it through nuget

**Comment by Alex-Dobrynin** [comment]
seems it is fixed in new visual studio
