### ISSUE TITLE
.NET 8 support?

### ISSUE THREAD

**Issue by SaifAqqad** [ArxOne/MrAdvice#198]
I'm getting an error when building my project:
| Severity | Code | Description | Project | File | Line | Suppression State |
| --- | --- | --- | --- | --- | --- | --- |
| Error | MSB3073 | The command `dotnet "C:\Users\user\.nuget\packages\mradvice\2.12.2\build\..\tools\net8.0/MrAdvice.Weaver.dll" AssemblyPath="obj\Debug\net8.0\project.dll" ReferencePath="@obj\Debug\net8.0\project.dll.MrAdvice.ReferencePath.txt" ReferenceCopyLocalPaths="@obj\Debug\net8.0\project.dll.MrAdvice.LocalReferencePath.txt" AssemblyOriginatorKeyFile="" SignAssembly="false"` exited with code 1. | project | C:\Users\user\\.nuget\packages\mradvice\2.12.2\build\MrAdvice.targets | 16 |  |
|  |

it seems the tools are not built for the target `net8.0` yet, however I think it should be possible to allow the tools for an older target version to be used to weave a newer target version (Fallback to highest tools version), in fact I worked around this issue (for now) by renaming the net7.0 tools folder to net8.0 and it worked fine.

**Comment by picrap** [comment]
That wound be great 😉. I’ll do it quickly.

**Comment by picrap** [comment]
Could you test version 2.13 and let me know?

**Comment by SaifAqqad** [comment]
![image](https://github.com/ArxOne/MrAdvice/assets/47293197/a3cf229b-5d59-45fd-b9f6-0a9aaf58e61a)
Works like a charm, thanks :D
