### ISSUE TITLE
PDB fails to load

### ISSUE THREAD

**Issue by rgroenewoudt** [ArxOne/MrAdvice#200]
We are running into a rare issue. We are using MrAdvice in our large solution in most projects but in 1 or 2 projects, the .pdb file fails to load while debugging in Visual Studio.

The Modules-windows in VS simply shows that PDB is not loaded and it fails loading it: `Unexpected error opening PDB file. The file may be corrupt.`
When MrAdvice nuget package is removed, it works again. Other similar projects always work.

The same issue occurs on my colleague's computers.

Things I've tried that make no difference:
- Full clean & remove bin/obj
- Change TargetFramework or RuntimeIdentifier

Comparing the DLLs in DotPeek with/without MrAdvice doesn't indicate anything. The one thing that is interesting is that System.Runtime shows up twice, 6.0.0.0 and 8.0.0.0 (we are using .NET 8) but this happens in all DLLs with MrAdvice.

I cannot reproduce this in a new project.

Do you have any suggestions on how to debug this? I can build MrAdvice locally and try out different things.

Running on:
- MrAdvice 2.14.0
- VS2022 17.8.5
- .NET 8.

**Comment by picrap** [comment]
Hi,

as far as I remember, this is related to PDB format. You can change it in build properties. Another PDB format may work.
Sorry for blurry answer.
Let me know!

**Comment by rgroenewoudt** [comment]
Well, the results are interesting. I've tried the [DebugType options](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#debugtype)
- default/portable: Fails for the specific project
- embedded: Also fails for the specific project. Other projects load fine and indicate embedded in VS.
- full: Works :)

My guess is that MrAdvice corrupts the new [portable pdb](https://github.com/dotnet/core/blob/main/Documentation/diagnostics/portable_pdb.md) in a rare case.
If I try the tool [sourcelink](https://github.com/ctaggart/SourceLink#source-link-testing-tool) with command `sourcelink print-urls pdb-file`, it works for other projects but fails with error "Read out of bounds." for the specific project. I'm cannot find any other tools to validate the portable-pdb-format.
I'm

**Comment by picrap** [comment]
MrAdvice is based on dnlib (https://github.com/0xd4d/dnlib) wich does the dirty work with PDB, so unfortunately this is not something I am comfortable with.
If one day there is something similar directly in dotnet, it may be worth trying to port it.

**Comment by rgroenewoudt** [comment]
Well, good news. I just spent 10 minutes updating dnlib to latest nuget (previous version was from 2020) in the Stitcherboy project and put the binaries in MrAdvice locally and debugging now works 👍 

I can make a PR for you in https://github.com/picrap/StitcherBoy.

**Comment by picrap** [comment]
That would be great! I’ll update MrAdvice after this. Thank you.

**Comment by picrap** [comment]
MrAdvice 2.15 is out! Let me know.

**Comment by rgroenewoudt** [comment]
Confirmed, the problem is fixed
