### ISSUE TITLE
Problem with constructor with 8 parameters.

### ISSUE THREAD

**Issue by rafallopatka** [ArxOne/MrAdvice#34]
Hi,

I received following error when i tried compile my project. 
It happens because constructor of some class has more than 8 parameters.

Error	11	Fody/MrAdvice.Weaver: Error while weaving method 'System.Void Mpos.Modules.Selling.ViewModels.ShoppingCart.ShoppingCartViewModel::.ctor(Mpos.Shared.Services.Contracts.Navigation.IBreadCrumb,Mpos.Shared.Services.Contracts.Dialogs.IBlockerService,Mpos.Shared.Services.Contracts.Logging.ILogger,Mpos.Shared.Model.Proxy.Events.IEventsService,Mpos.Shared.Model.Proxy.Reservation.IReservationService,Mpos.Shared.Services.Contracts.Dialogs.INotificationService,Mpos.Shared.Services.Contracts.Printer.IPrinterService,Mpos.Shared.Services.Contracts.Configuration.IConfigurationService,Mpos.Shared.Services.Contracts.User.ISessionManager,Mpos.Shared.Services.Contracts.Dialogs.IMessageDialogService)': System.ArgumentException: opcode
   w Mono.Cecil.Cil.Instruction.Create(OpCode opcode, Byte value)
   w ArxOne.MrAdvice.Weaver.Instructions.EmitLdc(Int32 value)
   w ArxOne.MrAdvice.Weaver.AspectWeaver.WritePointcutBody(MethodDefinition method, MethodDefinition innerMethod)
   w ArxOne.MrAdvice.Weaver.AspectWeaver.WeaveAdvices(MethodDefinition method)
   w ArxOne.MrAdvice.Weaver.AspectWeaver.WeaveMethod(ModuleDefinition moduleDefinition, MethodDefinition method, TypeDefinition adviceInterface)	Mpos.Modules.Selling

Best regards

**Comment by picrap** [comment]
I did a very simple class with an 8 arguments constructor but it works.
Could you provide a very simple class that fails weaving? Thanks.

**Comment by picrap** [comment]
OK, it was "more than 8". So I have reproduced the bug.

**Comment by picrap** [comment]
Fixed in 0.9.8.

**Comment by rafallopatka** [comment]
great thanks
