### ISSUE TITLE
MrAdvice abstract methods problem

### ISSUE THREAD

**Issue by rafallopatka** [ArxOne/MrAdvice#35]
I received following errors when i tried use MrAdvice with abstract method and property

[MyCustomAdvice]
abstract class Foo
{
        public abstract void InternalRefresh(bool bar = true);

        public abstract bool KeepAlive { get; }
}

Error	11	Fody/MrAdvice.Weaver: Error while weaving method 'System.Boolean Mpos.Modules.Common.ViewModels.Transactions.TransactionListViewModel::get_KeepAlive()': System.NullReferenceException: Object reference not set to an instance of an object.
   at ArxOne.MrAdvice.Weaver.AspectWeaver.WeaveAdvices(MethodDefinition method)
   at ArxOne.MrAdvice.Weaver.AspectWeaver.WeaveMethod(ModuleDefinition moduleDefinition, MethodDefinition method, TypeDefinition adviceInterface)	Mpos.Modules.Common

Error	10	Fody/MrAdvice.Weaver: Error while weaving method 'System.Void Mpos.Modules.Common.ViewModels.Transactions.TransactionListViewModel::InternalRefresh(System.Boolean)': System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w ArxOne.MrAdvice.Weaver.AspectWeaver.WeaveAdvices(MethodDefinition method)
   w ArxOne.MrAdvice.Weaver.AspectWeaver.WeaveMethod(ModuleDefinition moduleDefinition, MethodDefinition method, TypeDefinition adviceInterface)	Mpos.Modules.Common

Best Regards

**Comment by picrap** [comment]
Fixed. Abstract methods are no longer tried to be weaved (which does not make sense anyway).

**Comment by rafallopatka** [comment]
great thanks!
