### ISSUE TITLE
Error on extern methods

### ISSUE THREAD

**Issue by ste-art** [ArxOne/MrAdvice#40]
Example code:
```C#
    [MyAdvice]
    class Foo
    {
        [DllImport("msvcrt.dll", CallingConvention = CallingConvention.Cdecl)]
        public static extern int memcmp(byte[] b1, byte[] b2, UIntPtr count);
    }
```
Gives error:

    Error	1	Fody/MrAdvice.Weaver: Error while weaving method 'System.Int32 Example.Foo::memcmp(System.Byte[],System.Byte[],System.UIntPtr)': System.NullReferenceException: Object reference not set to an instance of an object.
    at ArxOne.MrAdvice.Weaver.AspectWeaver.WeaveAdvices(MarkedNode markedMethod)
    at ArxOne.MrAdvice.Weaver.AspectWeaver.WeaveMethod(ModuleDefinition moduleDefinition, MarkedNode markedMethod, TypeDefinition adviceInterface, Types types)	MrAdviceBug

**Comment by picrap** [comment]
Ouch (again)! Give me a few days to fix this.

**Comment by picrap** [comment]
Currently, PInvoke methods are excluded from weaving, but maybe one day I will make them fully weavable.
