### ISSUE TITLE
Library problem with Microsoft.Bcl.Build

### ISSUE THREAD

**Issue by Florismart** [ArxOne/MrAdvice#57]
Hi man, we had problem using MrAdvice with last microsoft.bcl.build nuget version (1.21) already installed.
Problem was that aspects were completly ignored!

P.S. we already skipped problem reinstalling an old microsoft.bcl.build package version (1.14)
I hope this can help improve your framework :+1:

**Comment by picrap** [comment]
Apparently I missed something: I setup a test project named `BclTest` with advices, and it works.
I suggest you download (or fork) the project, make your changes to `BclTest` until it stops working, and then I'll see what's going on.

**Comment by picrap** [comment]
Any news?
