### ISSUE TITLE
ExceptionAttribute

### ISSUE THREAD

**Issue by eaba** [ArxOne/MrAdvice#58]
@picrap How can i achieve exception handling with MrAdvice like PostSharp's OnExceptionAspect?
Kindly enlighten me further on AsyncAdvice and Exception handling with it. Thanks

**Comment by picrap** [comment]
Hi,

Mr. Advice was intended to be simple, so there is only one kind of advice, which must be implemented as a wrapper.
So if you want to catch exceptions, it is something like:
```csharp
public class SyncAdvice : Attribute, IMethodAdvice
{
    public void Advise(MethodAdviceContext context)
    {
      try
      {
        context.Proceed();
      }
      catch(WhatYouWantAsException)
      {
        // and do what you want as well
      }
    }
}
```
I currently havent tried exceptions with async behavior, so I keep this issue open until I come with a sample for async advices.

**Comment by eaba** [comment]
@picrap  in addition How would a retry work with MrAdvice?

**Comment by picrap** [comment]
You can invoke `context.Proceed()` several times.

**Comment by eaba** [comment]
Okay. Thanks
Please i will looking out for the Async Samples.
Thanks for your effort and Time spent on MrAdvice.
We will more documentation - detailed!

**Comment by eaba** [comment]
Please how do I pass value to the IntroducedField<T>?

**Comment by picrap** [comment]
Introduced fields are only available to the advice which introduced them (as detailed here: https://github.com/ArxOne/MrAdvice/wiki/IntroducingFields). They allow advices to keep data accross calls. Where do you want to take your introducted field value from?

**Comment by eaba** [comment]
I want to add the value when the attribute is applied like:
[SomeAdvice(Retry = 5)]
public bool someMethod()
{
}

**Comment by picrap** [comment]
I would say `MyIndroducedRetryField[context]=Retry`, for example. I assume that you will know how to initialize the field only once, by testing if it has already been set.

**Comment by eaba** [comment]
can this be done OUTSIDE the Advice class?

**Comment by picrap** [comment]
No.

**Comment by eaba** [comment]
Okay. I did not understand what i was doing before.
I was depending on IntroducedField<T> to pass my value
