### ISSUE TITLE
TaskCanceledException

### ISSUE THREAD

**Issue by eaba** [ArxOne/MrAdvice#59]
@picrap I have been experiencing TaskCanceledException with my Async Methods!
The Sync Methods work just fine when wrapped with MrAdvice Async Aspect!

I have also noticed that when i start getting TaskCanceledException the web application takes forever to load!

Thanks

**Comment by picrap** [comment]
How (by what) was the task cancelled?

**Comment by eaba** [comment]
For Instance this method when decorated with MrAdvice always timed out:
[MrAdvice]
public async Task<string> GetString()
{
   using(var con = new SqlConnection("connectionString")
   {
       await con.OpenAsync();
      using(var cmd = new SqlCommand("cmd", con)
      {
           var x = cmd.ExecuteScalarAsync();
           return x;
       }
    }
}
I decorated over 500 classes with MrAdvice. Before MrAdvice no issues and now without MrAdvice no issues!

**Comment by picrap** [comment]
So, if I understood: without Mr. Advice, the method has a timeout (`TimeoutException`?), and with Mr. Advice it has a `TaskCanceledException`, is it right?

**Comment by eaba** [comment]
The TaskCanceledException was due to TimeOutException.
the issue occurs with MrAdvice.
It is working perfectly without MrAdvice now. I am currently testing my methods and for over a hour no issues with TimeoutException or TaskCanceledException.
With MrAdvice it runs for few seconds and then deadlocks. Each time this happens i had to stop and start My Site Application Pool then it runs for few seconds again then deadlocks!

**Comment by picrap** [comment]
Hi, is the issue still there? Can you give it a try with version 2.0.16 (the package is `MrAdvice`, not `MrAdvice.Fody`)?
Thanks.
