### ISSUE TITLE
Invalid Cast for generic  types in out parameters of advised methods

### ISSUE THREAD

**Issue by texavery77** [ArxOne/MrAdvice#61]
MrAdvice will produce invalid Assemblys, when advising methods with generic out parameters, e.g. List<string>. The produced IL will contain a List<T> cast, a token, that cannot be resolved.

Error can be reproduced by following steps:

In class MethodLevelTests.BasicTests
void StaticMethodWithParameterTest():

Change signature of called method 
EmptyAdvisedClass.StaticMethodWithParameterTest

to

public static void StaticMethodWithParameterTest(int three, out List<string> ls)

and it will fail.

**Comment by picrap** [comment]
Thanks for reporting this. I'll take a look.

**Comment by texavery77** [comment]
What fixes the bug in my cases that I encountered up to now:

In Project MrAdvice.Weaver, file AspectWeaver.Weave.cs, method AspectWeaver.WritePointcutBody(MethodDefinition method, MethodDefinition innerMethod, bool abstractedTarget) at about line 360, I changed the out/ref parameters loop as follows:

`// loads back out/ref parameters
            for (int parameterIndex = 0; parameterIndex < method.Parameters.Count; parameterIndex++)
            {
                var parameter = method.Parameters[parameterIndex];
                if (parameter.ParameterType.IsByReference)
                {
                    instructions.EmitLdarg(parameter); // loads given parameter (it is a ref)
                    instructions.EmitLdloc(parametersVariable); // array
                    instructions.EmitLdc(parameterIndex); // array index
                    instructions.Emit(OpCodes.Ldelem_Ref); // now we have boxed out/ref value
                    var parameterElementType = parameter.ParameterType.GetElementType();

                    if (parameterElementType.HasGenericParameters)
                    {
                        ByReferenceType refType = (ByReferenceType) parameter.ParameterType;
                        GenericInstanceType genericType = (GenericInstanceType) refType.ElementType;                                               
                        instructions.EmitUnboxOrCastIfNecessary(genericType);
                        instructions.EmitStind(genericType); // result is stored in ref parameter
                    }                
                    else
                    {                      
                        instructions.EmitUnboxOrCastIfNecessary(parameterElementType);
                        instructions.EmitStind(parameterElementType); // result is stored in ref parameter
                    }                                      
                }
            }`
That provides for the fully resolved generic type in these cases.

**Comment by picrap** [comment]
Wow, and it works! Thanks for the fix, it is released in version 1.2.10.
If you meet other problems and you want to patch more efficiently, you can fork, fix and submit a pull request.

**Comment by picrap** [comment]
I have an unrelated question: do you like Mr. Advice? Do you have suggestions to improve it?

**Comment by texavery77** [comment]
I like Mr. Advice very much, as it was the perfect solution for a rather special problem, I had to solve.
Unfortunately, I just started using it  a few days ago, so it's difficult to make any further suggestions. Nonetheless, I hope to find more use cases that Mr. Advice can solve and if I stumble upon any "rough edges" or missing features I will let you know.
