### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by picrap** [ArxOne/MrAdvice#71]
Because right now, it's no 😢

**Comment by AlexanderButs** [comment]
Take into account project.json stuff - right now to make it working you should add post build step to project.json (because there is no msbuild for .NET Core and your build step is useless). But MS is planning to move project.json and xproj system back to msbuild and csproj. So read info about that first of all.

**Comment by picrap** [comment]
Some documentation: https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by picrap** [comment]
The best option is to wait for .NET Standard 2.0, which is supposed to be supported by all recent frameworks.

**Comment by DBCI** [comment]
Hello Pascal,

First, I want to say that MrAdvice is absolutely wonderful!  However, I need it to work with .NET Core projects and as such I've tried to add the MrAdvice target to my project and got the following result:

> warning : Can't load 'MrAdvice, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c0e7e6eab6f293d8'
> error : Internal error during Types import: System.NullReferenceException: Object reference not set to an instance of an object.
> error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.CreateWeavingContext(ModuleDefMD moduleDefinition)
> error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.Weave(ModuleDefMD moduleDefinition)

This appears at the build output right after the project properly builds.
I'm currently at a loss as to how I can resolve this, any ideas or comments would be great! :)

Again, wonderful product!

Thanks,
DB

**Comment by picrap** [comment]
Hi DB,
Yes I currently have the same problem and planned to work on it today. I'll let you know here when it is fixed.

And of course, I'm glad that you like Mr. Advice 👍

**Comment by picrap** [comment]
I've released a version 2.4.1-test1 which probably won't solve your problem (it solved mine, but I'm not sure they are the same).
If it still fails, could you provide me a simple project with the problem?

**Comment by DBCI** [comment]
Hello Pascal, and thanks for the speedy reply! :)

My issue is that I am actually trying to use MrAdvice (NuGet package 2.4.1-test1; just updated to it) in a .NET Core Console app project (*.xproj project.json files).

I took exactly the same code I've created when testing MrAdvice on my initial project (.NET Framework 4.6.1) and your NuGet package doesn't even modify the .NET Core project files to include the Weaver.

When I "forcibly" added the Weaver to the .NET Core project, that resulted in the error I showed you before. I will attempt to replicate this with your newest version and see what happens... stay tuned... ;)

**Comment by picrap** [comment]
Don't hurry, I think I have the exact same problem as you right now, so wait until a `-test2` version is available.

**Comment by DBCI** [comment]
OK, thanks...

By the way, have you started to adjust everything to work with the Mono.CeCIL .NET Core library version? Or do you have any other recommended CIL Re-writing Library you prefer working with?

**Comment by picrap** [comment]
My problem was just a debug parameter, so nothing to fix and no `-test2` needed right now, so you can probably use the `-test1`.
Regarding Cecil, I left it. Instead I use dnlib.

**Comment by DBCI** [comment]
Does dnlib support .NET Core?

**Comment by picrap** [comment]
Running from a .NET Core application? I have no idea...

**Comment by DBCI** [comment]
Thanks for the advice! :+1: I'll check dnlib out and see what I can come up with.

**Comment by DBCI** [comment]
Hi Pascal... my journey continues :wink:

This is what VS2015 reports when I build my DNC test project:

```
1>------ Rebuild All started: Project: AOPDNCTest, Configuration: Debug Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "C:\Users\dbarak\Source\Testing\AOPDNCTest\src\AOPDNCTest" --configuration Debug --no-dependencies --no-incremental
1>  Project AOPDNCTest (.NETCoreApp,Version=v1.0) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
1>  Compiling AOPDNCTest for .NETCoreApp,Version=v1.0
1>  Compilation succeeded.
1>      0 Warning(s)
1>      0 Error(s)
1>  Time elapsed 00:00:01.3288220
1>   (The compilation time can be improved. Run "dotnet build --build-profile" for more information)
1>  MrAdvice 2.4.0 weaved module 'AOPDNCTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' (targeting framework ) in 202ms
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```
And this happens as soon as I try to run the program:
```
{System.ArgumentException: Type passed in must be derived from System.Attribute or System.Attribute itself.
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at ArxOne.MrAdvice.PlatformUtility.GetAttributes[TAttribute](Type provider)
   at System.Linq.Enumerable.<SelectManyIterator>d__157`2.MoveNext()
   at System.Linq.Enumerable.UnionIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ArxOne.MrAdvice.Invocation.GetAllAdvices[TAdvice](MethodBase targetMethod, Tuple`2& relatedPropertyInfo)
   at ArxOne.MrAdvice.Invocation.GetAdvices[TAdvice](MethodBase targetMethod, Tuple`2& relatedPropertyInfo)
   at ArxOne.MrAdvice.Invocation.CreateAspectInfo(MethodBase method, RuntimeMethodHandle methodHandle, MethodInfo innerMethod, RuntimeMethodHandle innerMethodHandle, Boolean abstractedTarget)
   at ArxOne.MrAdvice.Invocation.GetAspectInfo(MethodBase method, RuntimeMethodHandle methodHandle, MethodBase innerMethod, RuntimeMethodHandle innerMethodHandle, Boolean abstractedTarget, Type[] genericArguments)
   at ArxOne.MrAdvice.Invocation.ProceedAdvice(Object target, Object[] parameters, RuntimeMethodHandle methodHandle, RuntimeMethodHandle innerMethodHandle, RuntimeTypeHandle typeHandle, Boolean abstractedTarget, Type[] genericArguments)
   at ArxOne.MrAdvice.⚡Invocation.ProceedAspect(Object , RuntimeMethodHandle , RuntimeMethodHandle )
   at AOPDNCTest.Computer.Compute()
   at AOPDNCTest.Program.Main(String[] args)}
```
Any ideas what's going on?

**Comment by picrap** [comment]
Probably: this means that I misused the `.GetCustomAttributes()` method. This should be fixed in version 2.4.3.

**Comment by DBCI** [comment]
I'll try to update to v2.4.3 and see how it goes... Thanks! :smile:

**Comment by picrap** [comment]
What package do you use? `Net40` or `NetStandard16`?
The problem with `dotnet build` is that I have no idea on how to work with it, since I don't know what NuGet can change to .NET Core projects (`xproj`, is that right?)

**Comment by DBCI** [comment]
OK, first of all there's a change in how the NuGet manager works with .NET Core projects. Instead of a "packages" directory that is a part of your solution folder-structure things get stored under the user-home directory. As if that's not enough, the invocation of the MrAdvice Weaver needs to slightly change as well so your old MrAdvice.Targets file requires some modifications.

I decided to create my own Targets file which I import at the end of my .xproj:

`<Import Project="MrAdvice.targets" Condition="Exists('MrAdvice.targets')" />`

This is what my Targets file contains:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <!-- The following properties should be read from Project files (*.xprj; project.json) -->
    <MrAdviceNetApp Condition="$(MrAdviceNetApp) == ''">netcoreapp1.0</MrAdviceNetApp>
    <MrAdviceTargetType Condition="$(OutputType) == 'Library'">.dll</MrAdviceTargetType>
    <MrAdviceTargetType Condition="$(OutputType) != 'Library'">.exe</MrAdviceTargetType>
    <MrAdviceTarget Condition="$(MrAdviceTarget) == ''">$(OutputPath)$(Configuration)\$(MrAdviceNetApp)\$(AssemblyName)$(MrAdviceTargetType)</MrAdviceTarget>

    <!-- The following properties should be read from the MrAdvice nuget package -->
    <MrAdviceVersion Condition="$(MrAdviceVersion) == ''">2.4.3</MrAdviceVersion>
    <MrAdviceNetStd Condition="$(MrAdviceNetStd) == ''">netstandard16</MrAdviceNetStd>
    <MrAdviceNuGetPath Condition="$(MrAdviceNuGetPath) == ''">$(USERPROFILE)\.nuget\packages\MrAdvice\</MrAdviceNuGetPath>
    <MrAdvicePath Condition="$(MrAdvicePath) == ''">$(MrAdviceNuGetPath)$(MrAdviceVersion)\</MrAdvicePath>
    <MrAdviceWeaver Condition="$(MrAdviceWeaver) == ''">$(MrAdvicePath)build\MrAdvice.Weaver.exe</MrAdviceWeaver>
    <MrAdviceDLL Condition="$(MrAdviceDLL) == ''">$(MrAdvicePath)lib\$(MrAdviceNetStd)\MrAdvice.dll</MrAdviceDLL>
  </PropertyGroup>

  <UsingTask TaskName="MrAdviceTask" AssemblyFile="$(MrAdviceWeaver)" />
  
  <Target Name="MrAdviceTarget" AfterTargets="CoreCompile" Outputs="@(IntermediateAssembly[0]).♥MrAdvice">
    <!-- The properties sent to MrAdvice.Weaver task may require tweaking? -->
    <MrAdviceTask
      AssemblyPath="$(MrAdviceTarget)"
      ReferencePath="$(MrAdviceDLL)"
      ReferenceCopyLocalPaths="@(ReferenceCopyLocalPaths)"
      AssemblyOriginatorKeyFile="$(AssemblyOriginatorKeyFile)"
      SignAssembly="$(SignAssembly)" />
  </Target>

</Project>
```
As you can see, I am using **NetStandard16**, and I'm happy to say that the same Targets file works for DNC App projects as well as DNC WebAPI projects! :grinning:

**Comment by DBCI** [comment]
I've included two test DNC projects that use MrAdvice... enjoy :wink: 
[AoPDnCSamples.zip](https://github.com/ArxOne/MrAdvice/files/637410/AoPDnCSamples.zip)

**Comment by DBCI** [comment]
Hi Pascal,

Just wanted to check if there are any new developments regarding MrAdvice and .NET Core projects (**NetAppCore1.0**/**NetStandard16**)?
Specifically if there's going to be a MrAdvice version (planned or otherwise) that will correctly integrate into the .NET Core project straight from the NuGet package?

Thanks,
DB

**Comment by picrap** [comment]
I'd love to! However, regarding all compatibility issues (and perhaps a part of laziness), I'll probably target NET Standard 2.0 only.

**Comment by picrap** [comment]
But if you're willing to help, you're welcome!

**Comment by DBCI** [comment]
Then until **NetStandard v2.0** comes, I'll continue to use my MrAdvice.targets file in my .NET Core projects.

Thanks for everything! :smile:

**Comment by DBCI** [comment]
OK, so I'm trying to figure out how to simplify and automate my **_MrAdvice.targets_** file and add it to a NuGet package/template... but I noticed something funny. I keep getting a warning when my projects include references to other DLL's.
For example:
`MrAdvice.targets(24,5): warning : Can't load 'Dapper, Version=1.50.2.0, Culture=neutral, PublicKeyToken=null'`

I assume what I'm doing wrong is passing only the reference to my own DLL instead of all the references participating in the project, but I'm not sure how to do that. Do **_ReferencePath_** or **_ReferenceCopyLocalPaths_** have anything to do with this?

**Comment by picrap** [comment]
Don't mind for this, I have the same issue, and I need to solve it... I think I may have left some debug information somewhere...

**Comment by DBCI** [comment]
I'm not worried about this regarding DLL's that are not supposed to contain my Advice attributes, but what about projects that have several DLL's in them that do contain multiple Advice attributes between them?

**Comment by picrap** [comment]
Does this happen?

**Comment by DBCI** [comment]
Yes. I just created a solution where the Console App project references a DLL I create in another project, both projects are under the same solution with the DLL project building before the Console App project, and while the Console App project is built the MrAdvice task complains about not being able to load/access my DLL.

**Comment by picrap** [comment]
OK, I'll take a look. However, if you can create a solution where the problem is reproductible, it may help.

**Comment by DBCI** [comment]
I'll try to create one without my proprietary code and post it. 😃

**Comment by DBCI** [comment]
Hey Pascal, Bonne Année! :grinning: 

I'm revisiting this issue and it actually seems related to the **ReferencePath** variable specified in the MrAdviceTask.

What I did was create two projects, one defining the advice attribute while the other uses the advice attribute. Once I tried building my solution like this I received an error telling me that the attribute/advice weaving failed.

When I added the DLL of the first project — the one defining the advice class — to the **ReferencePath** variable, the solution built properly and my program ran like it should have.

I guess I need to work on collecting all the DLL's involved in a project and feeding all of them to the weaver just like MSBuild does for a .NET Framework project! :crossed_fingers:

**Comment by DBCI** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <!-- Project Outputs and NuGet Setup -->
    <AppVersion Condition="$(AppVersion) == ''">netcoreapp1.0</AppVersion>
    <NetStdVersion Condition="$(NetStdVersion) == ''">netstandard16</NetStdVersion>
    <NuGetPath Condition="$(NuGetPath) == ''">$(USERPROFILE)\.nuget\packages\</NuGetPath>
    <!-- JsonPeek Setup -->
    <JsonPeekPath Condition="$(JsonPeekPath) == ''">$(NuGetPath)JsonPoke.MSBuild\1.0.7\build\</JsonPeekPath>
    <!-- MrAdvice Setup -->
    <MrAdvicePath Condition="$(MrAdvicePath) == ''">$(NuGetPath)MrAdvice\2.4.5\</MrAdvicePath>
  </PropertyGroup>
  <Import Project="$(JsonPeekPath)JsonPoke.MSBuild.Targets"/>
  <UsingTask TaskName="MrAdviceTask" AssemblyFile="$(MrAdvicePath)build\MrAdvice.Weaver.exe" />
  <Target Name="MrAdviceTarget" AfterTargets="CoreCompile" Outputs="@(IntermediateAssembly[0]).♥MrAdvice">
    <!-- Read the .IncrementalCache file to import project input files -->
    <JsonPeek JsonInputPath="$(BaseIntermediateOutputPath)$(Configuration)\$(AppVersion)\.IncrementalCache" JPath="inputs">
      <Output TaskParameter="Result" PropertyName="Inputs"/>
    </JsonPeek>
    <!-- Make an ItemGroup for the input files -->
    <ItemGroup>
      <InputFiles Include="$(Inputs)"/>
      <InputFiles Include="$(MrAdvicePath)lib\$(NetStdVersion)\MrAdvice.dll"/>
    </ItemGroup>
    <!-- Make a @(Reference) containing only DLL's -->
    <ItemGroup>
      <Reference Include="%(InputFiles.FullPath)" Condition="%(InputFiles.Extension) == '.dll'"/>
    </ItemGroup>
    <!-- Weave Advice -->
    <MrAdviceTask
      AssemblyPath="$(OutputPath)$(Configuration)\$(AppVersion)\$(TargetFileName)"
      ReferencePath="@(Reference)"
      ReferenceCopyLocalPaths="@(ReferenceCopyLocalPaths)"
      AssemblyOriginatorKeyFile="$(AssemblyOriginatorKeyFile)"
      SignAssembly="$(SignAssembly)" />
  </Target>
</Project>
```
OK, this one seems to do the trick. I had to add another 3rd party tool called JsonPeek/JsonPoke which is a pair of MSBuild task that allows the build process to read/write json files. This allows me to read the IncrementalCache file which holds information about project-inputs. Once I pass all DLL's from it plus the MrAdvice.dll everything seems to work, including loading advice attributes from another project! 😀 

This obviously requires more testing, and I'm sure can be improved upon, but for now it'll do. 😉

**Comment by DBCI** [comment]
Good news! I've created a Targets file that allows compilation and weaving of attributes in a .NET Core project that targets multiple platforms:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask TaskName="MrAdviceTask" AssemblyFile="$(USERPROFILE)\.nuget\packages\MrAdvice\2.4.5\build\MrAdvice.Weaver.exe" />
  <Target Name="CollectBinaryOutputs" AfterTargets="CoreCompile">
    <ItemGroup>
      <WorkFiles Include="$(OutputPath)$(Configuration)\**\$(TargetName).exe"/>
      <WorkFiles Include="$(OutputPath)$(Configuration)\**\$(TargetName).dll"/>
    </ItemGroup>
  </Target>
  <Target Name="MrAdviceTarget" AfterTargets="CollectBinaryOutputs" Inputs="%(WorkFiles.Identity)" Outputs="%(WorkFiles.Identity).♥MrAdvice">
    <PropertyGroup>
      <WorkFile>%(WorkFiles.Identity)</WorkFile>
      <ResponseFile>$(BaseIntermediateOutputPath)$(Configuration)\$([System.String]::new('$(WorkFile)').Split('\')[3])\dotnet-compile.rsp</ResponseFile>
    </PropertyGroup>
    <ReadLinesFromFile File="$(ResponseFile)">
      <Output TaskParameter="Lines" ItemName="ItemsFromFile"/>
    </ReadLinesFromFile>
    <ItemGroup>
      <RefLines Include="%(ItemsFromFile.Identity)" Condition="@(ItemsFromFile->StartsWith('--reference:')) == true"/>
      <ReferencePath Include="@(RefLines->Substring(12))"/>
    </ItemGroup>
    <MrAdviceTask
      AssemblyPath="$(WorkFile)"
      ReferencePath="@(ReferencePath)"
      ReferenceCopyLocalPaths="@(ReferenceCopyLocalPaths)"
      AssemblyOriginatorKeyFile="$(AssemblyOriginatorKeyFile)"
      SignAssembly="$(SignAssembly)" />
  </Target>
</Project>
```

This way the only configurable value required is the path to MrAdvice.Weaver.exe, while the rest is read from the project build output files.

If your .NET Core project targets **netcoreapp1.0** and **net461** for example, this Targets file will ensure all produced binaries are processed by MrAdvice.Weaver.

**Comment by Vololodia** [comment]
Hello, Pascal!
First of all I would like to say that your library is awesome)
But unfortunetly, I faced some problems when tried to use MrAdvice in .core projects. 
I know that officially MrAdvice still doesnt support .core projects, but possibly you know some workarounds or may be you can suggest some options.

For example we have one console app with simple Advice-Attribute. If I build project via VS standart build procedure - there is no problems - app would build and advice will correctly works.
But if instead of classic build we run "dotnet build" command in Package manager Console we got error - `error MSB4062: The "MrAdviceTask" task could not be loaded from the assembly C:\WINDOWS\system32\config\systemprofile\.nuget\packages\mradvice\2.5.19\build\..\build\MrAdvice.Weaver.exe. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask`
Solution that DBCI described (Change *.targets file) doesnt help, because after VS build (and after "dotnet build" too) Advice-Attribute doesnt do their job.
Actually I think that with changed *.targets file, MrAdviceTask even doesn't starts and there is no "post build effect" - because there is no "MrAdvice 2.5.19 weaved module " text in output.

I've created simple solution that demostrates the problem. One project for classic MrAdvice nuget implementation, and another for custom *.targets file.
[TimerTrace.zip](https://github.com/ArxOne/MrAdvice/files/1664370/TimerTrace.zip)

So my question: is there a way to resolve that problem?

**Comment by picrap** [comment]
I have no idea... Any help welcome 😉

**Comment by AlexanderButs** [comment]
Hey guys. Has anyone solved this problem (to use MrAdvice in .net core apps)?

**Comment by picrap** [comment]
Hi, it's totally untested, but as far as I can tell, if you build using `csproj`s Mr Advice does the job, whatever the target is.

**Comment by AlexanderButs** [comment]
Still have the same problem @Vololodia described above.

**Comment by picrap** [comment]
`dotnet build` is a pain in the ass (sorry about the words); since I don't use it, we're far from a fix... Except maybe if you want to contribute?

**Comment by AlexanderButs** [comment]
Got it. We are far from migrating from mono to dotnet core right now, but when we are close and we need to use MrAdvice on that platform of course I'll have a look. Even if I have know knowledge in all that build and target things :)

**Comment by picrap** [comment]
At work, we also use mono (and we're planning to move to .NET Core too), but all build is done from a Windows platform using `msbuild`. I took a look at `dotnet build` a long time ago, and as far as I remember, it was not really designed to accept extra build tasks (such as Mr. Advice weaver). But things may have changed...

**Comment by AlexanderButs** [comment]
As I know, dotnet build should call msbuild underneath, but I may be wrong.

**Comment by picrap** [comment]
Not sure of this, because `dotnet build` also exists on other platforms where `msbuild` does not.

**Comment by AlexanderButs** [comment]
At first peek it does. You can check it here https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-build/BuildCommand.cs

**Comment by soroshsabz** [comment]
I have the same issue on [Appveyor](https://ci.appveyor.com/project/soroshsabz/commons/builds/30004157) with MrAdvice 2.8.8

What is the last update to this issue? and is there any workaround about it?

**Comment by picrap** [comment]
We need help for this. First of all, the weaver should be able to run from command-line. Could you try? The documentation is here: https://github.com/ArxOne/MrAdvice/wiki/CommandLineWeaver

**Comment by soroshsabz** [comment]
No it couldn't run from command line, because 

`Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

**Comment by picrap** [comment]
Could you try with https://www.nuget.org/packages/MrAdvice/2.8.9-embed1 ? I've embedded some of required Microsoft assemblies.

**Comment by soroshsabz** [comment]
Another issue is I think https://github.com/microsoft/msbuild/issues/4786 we must change MrAdvice.NetStandard project type.

**Comment by picrap** [comment]
What problem do you have? Could you provide a log or anything that shows the error?

**Comment by soroshsabz** [comment]
If you open this project in visual studio 2019 you can see the error like below

`Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk.`

**Comment by soroshsabz** [comment]
I add PR #156 to resolve some issue in building this project under Visual Studio 2019 and netstandard 2

**Comment by soroshsabz** [comment]
> Could you try with https://www.nuget.org/packages/MrAdvice/2.8.9-embed1 ? I've embedded some of required Microsoft assemblies.

@picrap I upgrade my package to 2.8.9-embed1 but does not change anything

`C:\Users\sooro\.nuget\packages\mradvice\2.8.9-embed1\build\MrAdvice.targets(10,5): error MSB4062: The "MrAdviceTask" task could not be loaded from the assembly C:\Users\sooro\.nuget\packages\mradvice\2.8.9-embed1\build\..\build\MrAdvice.Weaver.exe. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\sooro\Documents\Visual Studio 2019\Projects\soroshsabz\Commons\Source\BSN.Commons\BSN.Commons.csproj]`

**Comment by soroshsabz** [comment]
@picrap I think the problem is https://github.com/Microsoft/msbuild/issues/2111#issuecomment-303438420

**Comment by picrap** [comment]
For information, I'm working on it. I'm currently moving the source library, `StitcherBoy` to pure .NET Standard, without any dependency, and after this, I'll embed the missing assemblies (`Microsoft.Build.*`) in MrAdvice package (still built for .NET 4.x (==.NET Standard 2.x), but without dependency)

**Comment by AlexanderButs** [comment]
Hey, Pascal, look at my forks. They are already ported to .net standard. I'm not sure embedding Microsoft.Build.* assemblies is a good idea, they may have another dependencies which require full net framework.

**Comment by picrap** [comment]
OK, "embedding" was the wrong term. I meant "include the dependencies as packages".

**Comment by picrap** [comment]
Also, I'm removing all references to `Microsoft.Build.*` in StitcherBoy, so it won't have any constraint.

**Comment by AlexanderButs** [comment]
But this won't work in .net core universe as I remembered.

**Comment by AlexanderButs** [comment]
Oh, I'm sorry. Yes, you need to consume nugets for net core and just reference assemblies for full framework. See my fork, it works.

**Comment by picrap** [comment]
Strange, because Microsoft packages depend on .NET Standard 2.0 and .NET framework 4.7.2. .NET Standard is supported by .NET Core, so it should work, shouldn't it?

**Comment by AlexanderButs** [comment]
I can make a pull request if you'd like. Just check my fork and if everything is ok i'll do this tomorrow.

**Comment by picrap** [comment]
I'd like to see if all dependencies can be removed from `StitcherBoy`, this is what I'm working on right now.

**Comment by AlexanderButs** [comment]
Great! Tell me if you need any help :)

**Comment by picrap** [comment]
@AlexanderButs it works, you can use version 2.9 with `dotnet build`

**Comment by AlexanderButs** [comment]
Hey, Pascal.

Unfortunately I can't verify your changes as I switched project and don't work with MrAdvice any more. But nice to hear you've done this. Good job!

Alex.

**Comment by soroshsabz** [comment]
@picrap Thanks for attention, but my question is which PR arrive this feature?

**Comment by picrap** [comment]
It is already working in release 2.9
