### ISSUE TITLE
Performance Optimization

### ISSUE THREAD

**Issue by buddde** [ArxOne/MrAdvice#74]
Hello,

thank you for your great MrAdvice. I love your tool.
I want to use MrAdvice for logging a lot of methods.
Unfortunately, it does not perform very well.

Can you please speed it up? As far as I can see, you call `MethodBase.GetCurrentMethod()` and `MethodBase.GetMethodFromHandle()` every time an "adviced" method is called.

Isn't it possible to cache this information? Maybe using a compiler-generated private static field or so. I cannot think of a situation in which the value changes between different calls.

kind regards,
buddde

**Comment by picrap** [comment]
Hi,

That's a good idea; I need to see how to do this. Using a cache would increase the code size, and I have in mind to reduce it. So the good thing to do would be to embed directly the method token. But for this, I need to make some research and tests 🏃.

Pascal.

**Comment by picrap** [comment]
Give https://www.nuget.org/packages/MrAdvice/2.1.0-pre1 a look.
(It was easier than I expected).

**Comment by buddde** [comment]
Thank you for your quick response.
I took a look at your new version 2.1.0-pre1 and the IL-code looks better now.

Unfortunately, I cannot measure any real performance boost, though it already is very fast.

I think, it is ok now and you can put it in the regular version.

**Comment by picrap** [comment]
What do you mean? Is it still too slow?

**Comment by buddde** [comment]
No, it is not "too" slow. Of course, it is slower than a "normal" method call, and that is fine. It is ok (and has been).

I was kind of curious whether this "static meta data" could be determined in a better, more efficient way.

**Comment by picrap** [comment]
OK, then. Case closed 😄
