### ISSUE TITLE
Relative path prevents seamless debugging

### ISSUE THREAD

**Issue by kondotak** [ArxOne/MrAdvice#79]
In a woven dll, the path pointing to the associated pdb file is relative.  This prevents any DLL deployed to the GAC (sharepoint) from properly debugging without explicitly pointing to a pdb via tool->options->debugging.  By default, VS2013 builds dll with absolute path for the pdb pointer, please mimic this behavior in woven dlls.

**Comment by picrap** [comment]
Hi Tak,

I answered to you yesterday and said to have fixed this issue in v2.3.2. Can you confirm it's OK for you?

**Comment by picrap** [comment]
Suspended to #78

**Comment by picrap** [comment]
Acknowledged in #78
