### ISSUE TITLE
Consider using IReadOnlyCollection<T> instead of IList<T>

### ISSUE THREAD

**Issue by TheXenocide** [ArxOne/MrAdvice#80]
I've been reading through the code trying to get an idea of what can and can't be done, what features are supported (slowly working my way toward info on async Task<T> handling) and I noticed several context properties like parameters/arguments use the IList type, but I suspect it might be a bit misleading to imply that advice can add new arguments to the call.  Most types that implement IList also implement IReadOnlyCollection (it's free, all the methods required by IReadOnlyCollection are already required by IList) so hopefully it won't require you to change much. Not a big deal, but figured it'd be better to recommend before a 1.0 milestone since the front page mentions the API is allowed to change during this time.

Also, if you would like some help documenting classes and usage, I don't have a lot of spare time, but I think that's something I might be able to offer.

**Comment by picrap** [comment]
Hi,

Thanks for suggestion. I took a look at occurrences of `List<>`, and the collections are actually read-write (`MethodAdviceContext.Arguments`, `MethodAsyncAdviceContext.Arguments` and `PropertyAdviceContext.Index`).
Did I miss something? Do you have a specific case in mind?

**Comment by TheXenocide** [comment]
What I mean is that an advice can't *actually* add new parameters to a method invocation, but the write-capable contract the property exposes (IList<T>) suggests they can. I don't think it's actually dangerous, but might be misleading, especially to less experienced .NET developers that might think, by adding values to the parameters collection they might force the calling code to execute a different overload than the method being intercepted. List<T> implements both IList<T> and IReadOnlyCollection<T>, but if you make the properties in MethodAdviceContext (and other contexts) return IReadOnlyCollection instead then it makes the idea clear to anybody making their own advice that these should not be changed.

That said, as I think about it, I suppose the collection may need to allow the values at individual indexes to be replaced since it might allow pre-processing transformation of parameter values, which IReadOnlyCollection doesn't allow. An Array would be a better choice, to imply the values at an index can be changed, but values can not be added or removed. In practice, it looks like these are backed by Arrays in the implementation (AdviceValues.Arguments), so they'll throw a NotSupportedException at runtime, if the IList<T>.Add method is called, but I think just changing MethodAdviceContext.Arguments (and properties like it) to object[] instead of IList<Object> would make it clear at design-time/compile-time, rather than run-time.

**Comment by picrap** [comment]
OK, I understand the problem, but as you said, there is no interface allowing to identify a fixed-size writable collection; so the remaining question (that you already asked too) is "is it better using directly an array?", and for me, the answer is "no". Since implementation may change, I prefer to stick to interfaces, even when they represent something incomplete.

**Comment by TheXenocide** [comment]
I think that's a fair position. For more complete documentation for consuming developers, I might recommend adding the information that items can be changed, but not added or removed, as remarks on the Arguments property (and other similar properties). 

I've been evaluating some AOP frameworks for work and, depending on the results of some practical tests, I'm hopeful we may begin using Mr. Advice on our next project. It's reassuring that you've responded so quickly; whether we use it at work or not, I hope to be able to contribute meaningfully so that AOP doesn't have to be such an expensive tool in the future. I'm thinking until I get to really using it, I'd like to improve the documentation around the API (which, I know is still in development, but should hopefully also make it easier for my coworkers). Would you be interested in this and, if so, do you have any preferences on documentation systems, build tools/scripts, etc. that I should consider? 

I'll just start with adding more information to the XML documentation tags for now, but there's a few ways that can be consumed to provide online or offline documentation (from robust [Doxygen](https://www.stack.nl/~dimitri/doxygen/manual/xmlcmds.html) outputs, to [this gist](https://gist.github.com/lontivero/593fc51f1208555112e0) which outputs simple markdown suitable for Github that looks [like this](https://github.com/formix/MegaCityOne/blob/master/MegaCityOne/doc/api.md)). I wouldn't mind writing some samples/tutorials along the way if that works for you. I've forked the repository and will start poking around soon, but no rush, just something to consider. I noticed you have http://mradvice.arxone.com/ which appears to use content from the Readme.md and my first instinct would be to produce something that fit well alongside that. I'll probably do some initial stuff just to get used to things and play around in the next couple days, so maybe be on the lookout for a pull request? :smile:

**Comment by picrap** [comment]
Oh, I must remove the link to http://mradvice.arxone.com, which is totally obsolete 😢 and directly link to GitHub page.
Any help welcome! XML doc is my favorite, since it appears in Visual Studio when using the methods, so yes, feel free to document! 👍 
Regarding a more exhaustive documentation, I started the wiki here, however it probably does not support pull requests, so I don't know what could be good to work with.

**Comment by TheXenocide** [comment]
I like the idea of keeping everything in one place, so I think I would recommend using [GitHub Pages with Jekyll](https://help.github.com/articles/about-github-pages-and-jekyll/), but for now I think I'll just work on XML docs and maybe play with the XML Doc->Markdown generator. GitHub has built in support for viewing Markdown files, so I think we probably just start simple with that and maybe decide if we like it when we see it? At least the XML Docs will stay useful, so not much waste if the Markdown/GitHub Pages it doesn't look ideal later.

**Comment by picrap** [comment]
As far as I remember, I used Jekyll to generate the site, however, it needs to be regenerated each time there is a change made to readme.md, this is why the site is not kept up to date, because I have to do it manually.

**Comment by TheXenocide** [comment]
Yeah, from what I can tell, I believe GitHub has made publishing easier to manage, but I think running Jekyll locally can sometimes be necessary to preview and troubleshoot; I believe you only need to commit/push Markdown files and publishing will automatically generate the HTML for the pages site based on your Jekyll settings in the repository. Since we're mostly talking about generated Markdown files, I think this should hopefully be a one-time setup cost, and hopefully generation of Markdown can maybe be part of the build so all we do is build source locally before committing (like we always should anyway) and that would generate any changes to the Markdown files along with the commit, then once the files are in master I think the github pages should just update automatically? It will take some experimenting, but I hope to make it painless

**Comment by picrap** [comment]
I updated the website, but it is still not automatic...

**Comment by TheXenocide** [comment]
Alas, ok. I will think on it more; there's plenty of work to do in the meantime. I have also found some other interesting tools. We have the option of just using Markdown files right in GitHub since the repository browser renders them fine by default ([example](https://github.com/lijunle/Vsxmd/blob/master/Vsxmd/Vsxmd.md#contents); no themes or anything, but that's all fluff I don't think developers will need too much). My adventure reading about the Markdown generator lead me to [Vsxmd](https://github.com/lijunle/Vsxmd) which looks interesting, but hasn't had any updates in awhile. From reading [this issue](https://github.com/lijunle/Vsxmd/issues/30) in the bug tracker, I am now looking into DocFX which is Micosoft's open source documentation generator they're using with all the new open source .NET Core stuff. I think this is probably the best choice because of the active Microsoft support/development and they support many output types (Markdown included). If we just use Markdown it will work without GitHub Pages, or we can generate the output and publish like normal; extra manual steps, but it looks like they have some nice ways to do it.

**Comment by picrap** [comment]
If you don't mind, I close the issue, since our conversation is far away from the original issue. We can still have a chat (I'm available by email or live/xmpp at the same address).
