### ISSUE TITLE
Weaved Assembly is incompatible with Fakes

### ISSUE THREAD

**Issue by kondotak** [ArxOne/MrAdvice#81]
Using the attached solution, perform the following steps to reproduce...
1) Navigate to TestProject
2) Right click SepDll in references -> "Add fakes assembly"

![image](https://cloud.githubusercontent.com/assets/17506502/20129062/00fa9a0c-a61b-11e6-908c-a796e1accd60.png)

[AOPMrAdvTest.zip](https://github.com/ArxOne/MrAdvice/files/580054/AOPMrAdvTest.zip)

**Comment by picrap** [comment]
Apparently this stupid bastard does not know how to deal with the elegance of Mr.Advice inner methods names (Mr. Advice adds new methods, whose name only differ from original name by an invisible space).
So the only solution is to change the way names are generated, and I don't like it 😞 
I need to make some more tests, and I'll let you know.

**Comment by picrap** [comment]
Solved in 2.3.5. Mr Advice lost its elegance, I lost my soul, but it works 😭
