### ISSUE TITLE
Error On Build.

### ISSUE THREAD

**Issue by Kahbazi** [ArxOne/MrAdvice#84]
I'm getting this error on build

warning : Can't load 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
error : Internal error during Weavable methods detection: System.InvalidCastException: Unable to cast object of type 'dnlib.DotNet.TypeSpecMD' to type 'dnlib.DotNet.TypeRef'.
error :    at ArxOne.MrAdvice.Weaver.TypeResolver.DoResolve(ITypeDefOrRef typeDefOrRef)
error :    at ArxOne.MrAdvice.Weaver.TypeResolver.Resolve(ITypeDefOrRef typeDefOrRef)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.IsMarker(ITypeDefOrRef typeReference, ITypeDefOrRef markerInterface)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass43_0.<IsMarker>b__0(InterfaceImpl i)
error :    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.IsMarker(ITypeDefOrRef typeReference, ITypeDefOrRef markerInterface)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.CreateAdviceSelector(ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.GetAdviceSelector(ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.CreateAdviceSelector(ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.GetAdviceSelector(ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.IsIncludedByNode(MarkerDefinition markerDefinition, ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass35_1.<GetMarkedMethods>b__4(MarkerDefinition d)
error :    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
error :    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
error :    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass35_0.<GetMarkedMethods>b__3(<>f__AnonymousType2`2 <>h__TransparentIdentifier0)
error :    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
error :    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
error :    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
error :    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
error :    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.Weave(ModuleDefMD moduleDefinition)
error : Please complain, whine, cry, yell at https://github.com/ArxOne/MrAdvice/issues/new

------------------------------------------

and this one 

error : Internal error during Weavable methods detection: System.InvalidCastException: Unable to cast object of type 'dnlib.DotNet.TypeSpecMD' to type 'dnlib.DotNet.TypeRef'.
error :    at ArxOne.MrAdvice.Weaver.TypeResolver.DoResolve(ITypeDefOrRef typeDefOrRef)
error :    at ArxOne.MrAdvice.Weaver.TypeResolver.Resolve(ITypeDefOrRef typeDefOrRef)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.IsMarker(ITypeDefOrRef typeReference, ITypeDefOrRef markerInterface)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass43_0.<IsMarker>b__0(InterfaceImpl i)
error :    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.IsMarker(ITypeDefOrRef typeReference, ITypeDefOrRef markerInterface)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.CreateAdviceSelector(ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.GetAdviceSelector(ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.CreateAdviceSelector(ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.GetAdviceSelector(ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.IsIncludedByNode(MarkerDefinition markerDefinition, ReflectionNode node, WeavingContext context)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass35_1.<GetMarkedMethods>b__4(MarkerDefinition d)
error :    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
error :    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
error :    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.<>c__DisplayClass35_0.<GetMarkedMethods>b__3(<>f__AnonymousType2`2 <>h__TransparentIdentifier0)
error :    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
error :    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
error :    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
error :    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
error :    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
error :    at ArxOne.MrAdvice.Weaver.AspectWeaver.Weave(ModuleDefMD moduleDefinition)
error : Please complain, whine, cry, yell at https://github.com/ArxOne/MrAdvice/issues/new

**Comment by picrap** [comment]
✔️ Problem reproduced.
❌ Problem still to be solved.
⌛️ Please wait...

**Comment by picrap** [comment]
✔️ Problem solved in 2.4.2
Thanks for reporting it 👍
