### ISSUE TITLE
Advice on assembly, literally advice all methods

### ISSUE THREAD

**Issue by Kahbazi** [ArxOne/MrAdvice#85]
when I Advice on an assembly , if I understand correctly, it will look through assembly and advice all methods.
These methods also contains all the setter and getter, and also (since I'm using Async) methods like SetStateMachine and MoveNext which is compiler generated.

It will be nice if there will be an attribute to exclude Advicing Setter and getter. and also I myself don't see any reason for SetStateMachine and MoveNext to be adviced. maybe it could be disable for default, and only be enabled if needed.

**Comment by picrap** [comment]
Yes, that's the point: applying an advice to an assembly advises all of it 😉 
If you want to exclude specific methods from being advised, there is an `[ExcludePointcut]` attribute that you can apply to your advice.
For example, if you want to avoid advising property getters and setters, simply add this to your advices:
```csharp
[ExcludePointcut("*.get_@", "*.set_@")]
public class MyAdvice: Attribute, IMethodAdvice
{
  // blah blah blah
}
```

The attribute is currently documented [here](https://github.com/ArxOne/MrAdvice/issues/75) (but right, I need to add it to the wiki).
