### ISSUE TITLE
MrAdvice as transitive dependency fails build

### ISSUE THREAD

**Issue by tpluscode** [ArxOne/MrAdvice#93]
We have a project, which references an internal package (let's call it `Lib`). `Lib` references uses MrAdvice to create shared aspects. The project has reference to both `Lib` and MrAdvice but that particular project doesn't actually use the attribute. When building we get these four errors:

```
ExecutionPointAttribute default ctor was not found 
ExcludePointcutAttributeType was not found 
IncludePointcutAttributeType was not found 
ExcludeAdviceAttributeType was not found 
```

What is the cause?

**Comment by picrap** [comment]
I guess you work with .NET Core?

**Comment by tpluscode** [comment]
Oh, no. net45. MrAdvice 2.4.5

⁣-- 
Tomasz Pluskiewicz ​

**Comment by picrap** [comment]
OK, I'll check this. As a temporary fix, just make a reference to MrAdvice in you main assembly, for exemple `var dummy = typeof(IAdvice);` in your `Main()` method should do the trick.

**Comment by picrap** [comment]
I created a very small solution with a configuration identical to the one you described (`ConsoleApplication8` references `ClassLibrary1` which uses MrAdvice, but the application does not reference any MrAdvice type directly).
Unfortunately, this builds successfully. What's wrong with my test? Please find it attached.
[ConsoleApplication8.zip](https://github.com/ArxOne/MrAdvice/files/835104/ConsoleApplication8.zip)

**Comment by tpluscode** [comment]
Strange. We reference the library via NuGet package but I tried and failed to reproduce in your attached example.

**Comment by picrap** [comment]
So do you have a failing sample? How can we proceed on this?

**Comment by tpluscode** [comment]
Unfortunately I don't. Not really sure how our repository is different. It's not being a big pain for us. Feel free to close
