### ISSUE TITLE
ExecutionPointAttribute is not derived from Attribute (Protobuf.net claims)

### ISSUE THREAD

**Issue by hhblaze** [ArxOne/MrAdvice#95]
While deserializing POCO object morphed by MrAdvice, protobuf shouts:

An exception of type 'ProtoBuf.ProtoException' occurred in protobuf-net.dll but was not handled in user code
Additional information: can't cast type "ArxOne.MrAdvice.Annotation.ExecutionPointAttribute" to type "System.Attribute".

**Comment by picrap** [comment]
Wow! This is a bug and a shameful one! I just released a new version with the fix. Sorry for that.

**Comment by hhblaze** [comment]
Thank you, will test when it's available via NuGet.

**Comment by hhblaze** [comment]
Works!
