### ISSUE TITLE
Supplying custom attribute to Mr.Advice and binding it to the concept.

### ISSUE THREAD

**Issue by hhblaze** [ArxOne/MrAdvice#99]
In my case objects are POCO and designed to be serialized and moved between different software tiers, not any of the tier has Mr.Advice installed, but such classes must be compiled without Mr.Advice. It (may be) should mean that there going to be a way to create decorating attributes outside of Mr.Advice and then supply them to Mr.Advice via configuration.

.. taken from
https://github.com/ArxOne/MrAdvice/issues/97#issuecomment-286679643

**Comment by picrap** [comment]
A much simpler way would be to embed all MrAdvice code as internal in the weaved assembly.
However this would cause problems when multiple assemblies processed with MrAdvice reference each other.

**Comment by hhblaze** [comment]
One of ideas is here https://github.com/ArxOne/MrAdvice/issues/98
